// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


let someString = "hello";

let createdDict = {
  name: "hello",
  age: "what",
  more: "stuff",
  otherStr: someString
};

let intDict = {
  one: 1,
  two: 2,
  three: 3
};

function inferDictByPattern(dict) {
  let match = dict.one;
  if (match === 1) {
    console.log("one");
  } else {
    console.log("not one");
  }
}

function constrainedAsDict(dict) {
  let match = dict.one;
  if (match === 1) {
    console.log("one");
  } else {
    console.log("not one");
  }
}

let PatternMatching = {
  inferDictByPattern: inferDictByPattern,
  constrainedAsDict: constrainedAsDict
};

let three = 3;

exports.someString = someString;
exports.createdDict = createdDict;
exports.three = three;
exports.intDict = intDict;
exports.PatternMatching = PatternMatching;
/* No side effect */
