// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_dict = require("../../lib/js/js_dict.js");

var dictCreationCanNotBeInlined = Js_dict.fromArray(imaginary);

var dictCreationCanBeInlined = {
  name: "hello",
  age: "what",
  more: "stuff"
};

exports.dictCreationCanBeInlined = dictCreationCanBeInlined;
exports.dictCreationCanNotBeInlined = dictCreationCanNotBeInlined;
/* dictCreationCanNotBeInlined Not a pure module */
