// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


let a = Math.pow(2, Math.pow(3, 2));

let b = Math.pow(2, Math.pow(-3, 2));

let c = Math.pow(Math.pow(2, 3), 2);

let d = Math.pow(-2, 2);

exports.a = a;
exports.b = b;
exports.c = c;
exports.d = d;
/* a Not a pure module */
