// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


let overflow_dec_i32_number = 272872590;

let overflow_dec_i32_number_2 = 0;

let not_overflow_dec_i32_number_3 = -1;

let overflow_hex_i32_number = -1;

exports.overflow_dec_i32_number = overflow_dec_i32_number;
exports.overflow_dec_i32_number_2 = overflow_dec_i32_number_2;
exports.not_overflow_dec_i32_number_3 = not_overflow_dec_i32_number_3;
exports.overflow_hex_i32_number = overflow_hex_i32_number;
/* No side effect */
