// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Primitive_object = require("../../lib/js/primitive_object.js");
let Primitive_option = require("../../lib/js/primitive_option.js");

if (!Primitive_object.equal(Primitive_option.nullable_to_opt(""), "")) {
  throw {
    RE_EXN_ID: "Assert_failure",
    _1: [
      "gpr_974_test.res",
      2,
      2
    ],
    Error: new Error()
  };
}

if (!Primitive_object.equal(Primitive_option.undefined_to_opt(""), "")) {
  throw {
    RE_EXN_ID: "Assert_failure",
    _1: [
      "gpr_974_test.res",
      3,
      2
    ],
    Error: new Error()
  };
}

if (!Primitive_object.equal(Primitive_option.null_to_opt(""), "")) {
  throw {
    RE_EXN_ID: "Assert_failure",
    _1: [
      "gpr_974_test.res",
      4,
      2
    ],
    Error: new Error()
  };
}

/*  Not a pure module */
