// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var T0_myList = {
  hd: 1,
  tl: {
    hd: 2,
    tl: /* [] */0
  }
};

var T0_tail = {
  hd: 2,
  tl: /* [] */0
};

var T0 = {
  myList: T0_myList,
  head: 1,
  tail: T0_tail
};

throw {
      RE_EXN_ID: "Match_failure",
      _1: [
        "gpr_4632.res",
        12,
        6
      ],
      Error: new Error()
    };

exports.T0 = T0;
exports.T1 = T1;
/* T1 Not a pure module */
