// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function f(x) {
  return x + 1 | 0;
}

var a = f(1);

var b = f(2);

function g(param) {
  return 1;
}

var c = g();

var d = g();

exports.f = f;
exports.a = a;
exports.b = b;
exports.g = g;
exports.c = c;
exports.d = d;
/* a Not a pure module */
