// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Caml_js_exceptions = require("../../lib/js/caml_js_exceptions.js");

function isA(c) {
  if (c === 97) {
    return true;
  }
  throw Caml_js_exceptions.internalFromExtension({
    RE_EXN_ID: "Match_failure",
    _1: [
      "gpr_5557.res",
      5,
      2
    ]
  });
}

let h = /* 'a' */97;

exports.isA = isA;
exports.h = h;
/* No side effect */
