// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function actionKey(key, a, b, c, d, e) {
  switch (key) {
    case 98 :
        return c;
    case 106 :
        return d;
    case 107 :
        return e;
    case 116 :
        return b;
    case 99 :
    case 118 :
        return a;
    default:
      
  }
  return function (param) {
    
  };
}

exports.actionKey = actionKey;
/* No side effect */
