// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var MyCssCss = require("./myCss.css");
var MyJsonJson = require("./myJson.json").default;

var myJson = MyJsonJson;

console.log(myJson);

var buttonCss = MyCssCss.button;

console.log(buttonCss);

exports.myJson = myJson;
exports.buttonCss = buttonCss;
/* myJson Not a pure module */
