// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


console.log("list");

console.log("list");

function f(x) {
  if (x !== undefined) {
    return "Some";
  } else {
    return "None";
  }
}

console.log([
  f(3),
  "None",
  "Some"
]);

console.log([
  "A",
  (function (x) {
    switch (x.TAG) {
      case "A" :
          return "A";
      case "B" :
          return "B";
      default:
        return "?";
    }
  })({
    TAG: "A",
    _0: 3
  })
]);

/*  Not a pure module */
