// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


let N = {};

let hh = "hellohello";

console.log([
  3e-6,
  3e-6
]);

let x = true;

function N1(funarg) {
  return {};
}

let h = "hello";

exports.x = x;
exports.N = N;
exports.N1 = N1;
exports.h = h;
exports.hh = hh;
/*  Not a pure module */
