// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Mt = require("./mt.js");
let Js_math = require("../../lib/js/js_math.js");

let suites_0 = [
  "_E",
  (param => {
    return {
      TAG: "ApproxThreshold",
      _0: 0.001,
      _1: 2.718,
      _2: Math.E
    };
  })
];

let suites_1 = {
  hd: [
    "_LN2",
    (param => {
      return {
        TAG: "ApproxThreshold",
        _0: 0.001,
        _1: 0.693,
        _2: Math.LN2
      };
    })
  ],
  tl: {
    hd: [
      "_LN10",
      (param => {
        return {
          TAG: "ApproxThreshold",
          _0: 0.001,
          _1: 2.303,
          _2: Math.LN10
        };
      })
    ],
    tl: {
      hd: [
        "_LOG2E",
        (param => {
          return {
            TAG: "ApproxThreshold",
            _0: 0.001,
            _1: 1.443,
            _2: Math.LOG2E
          };
        })
      ],
      tl: {
        hd: [
          "_LOG10E",
          (param => {
            return {
              TAG: "ApproxThreshold",
              _0: 0.001,
              _1: 0.434,
              _2: Math.LOG10E
            };
          })
        ],
        tl: {
          hd: [
            "_PI",
            (param => {
              return {
                TAG: "ApproxThreshold",
                _0: 0.00001,
                _1: 3.14159,
                _2: Math.PI
              };
            })
          ],
          tl: {
            hd: [
              "_SQRT1_2",
              (param => {
                return {
                  TAG: "ApproxThreshold",
                  _0: 0.001,
                  _1: 0.707,
                  _2: Math.SQRT1_2
                };
              })
            ],
            tl: {
              hd: [
                "_SQRT2",
                (param => {
                  return {
                    TAG: "ApproxThreshold",
                    _0: 0.001,
                    _1: 1.414,
                    _2: Math.SQRT2
                  };
                })
              ],
              tl: {
                hd: [
                  "abs_int",
                  (param => {
                    return {
                      TAG: "Eq",
                      _0: 4,
                      _1: Math.abs(-4)
                    };
                  })
                ],
                tl: {
                  hd: [
                    "abs_float",
                    (param => {
                      return {
                        TAG: "Eq",
                        _0: 1.2,
                        _1: Math.abs(-1.2)
                      };
                    })
                  ],
                  tl: {
                    hd: [
                      "acos",
                      (param => {
                        return {
                          TAG: "ApproxThreshold",
                          _0: 0.001,
                          _1: 1.159,
                          _2: Math.acos(0.4)
                        };
                      })
                    ],
                    tl: {
                      hd: [
                        "acosh",
                        (param => {
                          return {
                            TAG: "ApproxThreshold",
                            _0: 0.001,
                            _1: 0.622,
                            _2: Math.acosh(1.2)
                          };
                        })
                      ],
                      tl: {
                        hd: [
                          "asin",
                          (param => {
                            return {
                              TAG: "ApproxThreshold",
                              _0: 0.001,
                              _1: 0.411,
                              _2: Math.asin(0.4)
                            };
                          })
                        ],
                        tl: {
                          hd: [
                            "asinh",
                            (param => {
                              return {
                                TAG: "ApproxThreshold",
                                _0: 0.001,
                                _1: 0.390,
                                _2: Math.asinh(0.4)
                              };
                            })
                          ],
                          tl: {
                            hd: [
                              "atan",
                              (param => {
                                return {
                                  TAG: "ApproxThreshold",
                                  _0: 0.001,
                                  _1: 0.380,
                                  _2: Math.atan(0.4)
                                };
                              })
                            ],
                            tl: {
                              hd: [
                                "atanh",
                                (param => {
                                  return {
                                    TAG: "ApproxThreshold",
                                    _0: 0.001,
                                    _1: 0.423,
                                    _2: Math.atanh(0.4)
                                  };
                                })
                              ],
                              tl: {
                                hd: [
                                  "atan2",
                                  (param => {
                                    return {
                                      TAG: "ApproxThreshold",
                                      _0: 0.001,
                                      _1: 0.588,
                                      _2: Math.atan2(0.4, 0.6)
                                    };
                                  })
                                ],
                                tl: {
                                  hd: [
                                    "cbrt",
                                    (param => {
                                      return {
                                        TAG: "Eq",
                                        _0: 2,
                                        _1: Math.cbrt(8)
                                      };
                                    })
                                  ],
                                  tl: {
                                    hd: [
                                      "unsafe_ceil_int",
                                      (param => {
                                        return {
                                          TAG: "Eq",
                                          _0: 4,
                                          _1: Math.ceil(3.2)
                                        };
                                      })
                                    ],
                                    tl: {
                                      hd: [
                                        "ceil_int",
                                        (param => {
                                          return {
                                            TAG: "Eq",
                                            _0: 4,
                                            _1: Js_math.ceil_int(3.2)
                                          };
                                        })
                                      ],
                                      tl: {
                                        hd: [
                                          "ceil_float",
                                          (param => {
                                            return {
                                              TAG: "Eq",
                                              _0: 4,
                                              _1: Math.ceil(3.2)
                                            };
                                          })
                                        ],
                                        tl: {
                                          hd: [
                                            "cos",
                                            (param => {
                                              return {
                                                TAG: "ApproxThreshold",
                                                _0: 0.001,
                                                _1: 0.921,
                                                _2: Math.cos(0.4)
                                              };
                                            })
                                          ],
                                          tl: {
                                            hd: [
                                              "cosh",
                                              (param => {
                                                return {
                                                  TAG: "ApproxThreshold",
                                                  _0: 0.001,
                                                  _1: 1.081,
                                                  _2: Math.cosh(0.4)
                                                };
                                              })
                                            ],
                                            tl: {
                                              hd: [
                                                "exp",
                                                (param => {
                                                  return {
                                                    TAG: "ApproxThreshold",
                                                    _0: 0.001,
                                                    _1: 1.491,
                                                    _2: Math.exp(0.4)
                                                  };
                                                })
                                              ],
                                              tl: {
                                                hd: [
                                                  "expm1",
                                                  (param => {
                                                    return {
                                                      TAG: "ApproxThreshold",
                                                      _0: 0.001,
                                                      _1: 0.491,
                                                      _2: Math.expm1(0.4)
                                                    };
                                                  })
                                                ],
                                                tl: {
                                                  hd: [
                                                    "unsafe_floor_int",
                                                    (param => {
                                                      return {
                                                        TAG: "Eq",
                                                        _0: 3,
                                                        _1: Math.floor(3.2)
                                                      };
                                                    })
                                                  ],
                                                  tl: {
                                                    hd: [
                                                      "floor_int",
                                                      (param => {
                                                        return {
                                                          TAG: "Eq",
                                                          _0: 3,
                                                          _1: Js_math.floor_int(3.2)
                                                        };
                                                      })
                                                    ],
                                                    tl: {
                                                      hd: [
                                                        "floor_float",
                                                        (param => {
                                                          return {
                                                            TAG: "Eq",
                                                            _0: 3,
                                                            _1: Math.floor(3.2)
                                                          };
                                                        })
                                                      ],
                                                      tl: {
                                                        hd: [
                                                          "fround",
                                                          (param => {
                                                            return {
                                                              TAG: "Approx",
                                                              _0: 3.2,
                                                              _1: Math.fround(3.2)
                                                            };
                                                          })
                                                        ],
                                                        tl: {
                                                          hd: [
                                                            "hypot",
                                                            (param => {
                                                              return {
                                                                TAG: "ApproxThreshold",
                                                                _0: 0.001,
                                                                _1: 0.721,
                                                                _2: Math.hypot(0.4, 0.6)
                                                              };
                                                            })
                                                          ],
                                                          tl: {
                                                            hd: [
                                                              "hypotMany",
                                                              (param => {
                                                                return {
                                                                  TAG: "ApproxThreshold",
                                                                  _0: 0.001,
                                                                  _1: 1.077,
                                                                  _2: Math.hypot(0.4, 0.6, 0.8)
                                                                };
                                                              })
                                                            ],
                                                            tl: {
                                                              hd: [
                                                                "imul",
                                                                (param => {
                                                                  return {
                                                                    TAG: "Eq",
                                                                    _0: 8,
                                                                    _1: Math.imul(4, 2)
                                                                  };
                                                                })
                                                              ],
                                                              tl: {
                                                                hd: [
                                                                  "log",
                                                                  (param => {
                                                                    return {
                                                                      TAG: "ApproxThreshold",
                                                                      _0: 0.001,
                                                                      _1: -0.916,
                                                                      _2: Math.log(0.4)
                                                                    };
                                                                  })
                                                                ],
                                                                tl: {
                                                                  hd: [
                                                                    "log1p",
                                                                    (param => {
                                                                      return {
                                                                        TAG: "ApproxThreshold",
                                                                        _0: 0.001,
                                                                        _1: 0.336,
                                                                        _2: Math.log1p(0.4)
                                                                      };
                                                                    })
                                                                  ],
                                                                  tl: {
                                                                    hd: [
                                                                      "log10",
                                                                      (param => {
                                                                        return {
                                                                          TAG: "ApproxThreshold",
                                                                          _0: 0.001,
                                                                          _1: -0.397,
                                                                          _2: Math.log10(0.4)
                                                                        };
                                                                      })
                                                                    ],
                                                                    tl: {
                                                                      hd: [
                                                                        "log2",
                                                                        (param => {
                                                                          return {
                                                                            TAG: "ApproxThreshold",
                                                                            _0: 0.001,
                                                                            _1: -1.321,
                                                                            _2: Math.log2(0.4)
                                                                          };
                                                                        })
                                                                      ],
                                                                      tl: {
                                                                        hd: [
                                                                          "max_int",
                                                                          (param => {
                                                                            return {
                                                                              TAG: "Eq",
                                                                              _0: 4,
                                                                              _1: Math.max(2, 4)
                                                                            };
                                                                          })
                                                                        ],
                                                                        tl: {
                                                                          hd: [
                                                                            "maxMany_int",
                                                                            (param => {
                                                                              return {
                                                                                TAG: "Eq",
                                                                                _0: 4,
                                                                                _1: Math.max(2, 4, 3)
                                                                              };
                                                                            })
                                                                          ],
                                                                          tl: {
                                                                            hd: [
                                                                              "max_float",
                                                                              (param => {
                                                                                return {
                                                                                  TAG: "Eq",
                                                                                  _0: 4.2,
                                                                                  _1: Math.max(2.7, 4.2)
                                                                                };
                                                                              })
                                                                            ],
                                                                            tl: {
                                                                              hd: [
                                                                                "maxMany_float",
                                                                                (param => {
                                                                                  return {
                                                                                    TAG: "Eq",
                                                                                    _0: 4.2,
                                                                                    _1: Math.max(2.7, 4.2, 3.9)
                                                                                  };
                                                                                })
                                                                              ],
                                                                              tl: {
                                                                                hd: [
                                                                                  "min_int",
                                                                                  (param => {
                                                                                    return {
                                                                                      TAG: "Eq",
                                                                                      _0: 2,
                                                                                      _1: Math.min(2, 4)
                                                                                    };
                                                                                  })
                                                                                ],
                                                                                tl: {
                                                                                  hd: [
                                                                                    "minMany_int",
                                                                                    (param => {
                                                                                      return {
                                                                                        TAG: "Eq",
                                                                                        _0: 2,
                                                                                        _1: Math.min(2, 4, 3)
                                                                                      };
                                                                                    })
                                                                                  ],
                                                                                  tl: {
                                                                                    hd: [
                                                                                      "min_float",
                                                                                      (param => {
                                                                                        return {
                                                                                          TAG: "Eq",
                                                                                          _0: 2.7,
                                                                                          _1: Math.min(2.7, 4.2)
                                                                                        };
                                                                                      })
                                                                                    ],
                                                                                    tl: {
                                                                                      hd: [
                                                                                        "minMany_float",
                                                                                        (param => {
                                                                                          return {
                                                                                            TAG: "Eq",
                                                                                            _0: 2.7,
                                                                                            _1: Math.min(2.7, 4.2, 3.9)
                                                                                          };
                                                                                        })
                                                                                      ],
                                                                                      tl: {
                                                                                        hd: [
                                                                                          "random",
                                                                                          (param => {
                                                                                            let a = Math.random();
                                                                                            return {
                                                                                              TAG: "Ok",
                                                                                              _0: a >= 0 && a < 1
                                                                                            };
                                                                                          })
                                                                                        ],
                                                                                        tl: {
                                                                                          hd: [
                                                                                            "random_int",
                                                                                            (param => {
                                                                                              let a = Js_math.random_int(1, 3);
                                                                                              return {
                                                                                                TAG: "Ok",
                                                                                                _0: a >= 1 && a < 3
                                                                                              };
                                                                                            })
                                                                                          ],
                                                                                          tl: {
                                                                                            hd: [
                                                                                              "unsafe_round",
                                                                                              (param => {
                                                                                                return {
                                                                                                  TAG: "Eq",
                                                                                                  _0: 3,
                                                                                                  _1: Math.round(3.2)
                                                                                                };
                                                                                              })
                                                                                            ],
                                                                                            tl: {
                                                                                              hd: [
                                                                                                "round",
                                                                                                (param => {
                                                                                                  return {
                                                                                                    TAG: "Eq",
                                                                                                    _0: 3,
                                                                                                    _1: Math.round(3.2)
                                                                                                  };
                                                                                                })
                                                                                              ],
                                                                                              tl: {
                                                                                                hd: [
                                                                                                  "sign_int",
                                                                                                  (param => {
                                                                                                    return {
                                                                                                      TAG: "Eq",
                                                                                                      _0: -1,
                                                                                                      _1: Math.sign(-4)
                                                                                                    };
                                                                                                  })
                                                                                                ],
                                                                                                tl: {
                                                                                                  hd: [
                                                                                                    "sign_float",
                                                                                                    (param => {
                                                                                                      return {
                                                                                                        TAG: "Eq",
                                                                                                        _0: -1,
                                                                                                        _1: Math.sign(-4.2)
                                                                                                      };
                                                                                                    })
                                                                                                  ],
                                                                                                  tl: {
                                                                                                    hd: [
                                                                                                      "sign_float -0",
                                                                                                      (param => {
                                                                                                        return {
                                                                                                          TAG: "Eq",
                                                                                                          _0: -0,
                                                                                                          _1: Math.sign(-0)
                                                                                                        };
                                                                                                      })
                                                                                                    ],
                                                                                                    tl: {
                                                                                                      hd: [
                                                                                                        "sin",
                                                                                                        (param => {
                                                                                                          return {
                                                                                                            TAG: "ApproxThreshold",
                                                                                                            _0: 0.001,
                                                                                                            _1: 0.389,
                                                                                                            _2: Math.sin(0.4)
                                                                                                          };
                                                                                                        })
                                                                                                      ],
                                                                                                      tl: {
                                                                                                        hd: [
                                                                                                          "sinh",
                                                                                                          (param => {
                                                                                                            return {
                                                                                                              TAG: "ApproxThreshold",
                                                                                                              _0: 0.001,
                                                                                                              _1: 0.410,
                                                                                                              _2: Math.sinh(0.4)
                                                                                                            };
                                                                                                          })
                                                                                                        ],
                                                                                                        tl: {
                                                                                                          hd: [
                                                                                                            "sqrt",
                                                                                                            (param => {
                                                                                                              return {
                                                                                                                TAG: "ApproxThreshold",
                                                                                                                _0: 0.001,
                                                                                                                _1: 0.632,
                                                                                                                _2: Math.sqrt(0.4)
                                                                                                              };
                                                                                                            })
                                                                                                          ],
                                                                                                          tl: {
                                                                                                            hd: [
                                                                                                              "tan",
                                                                                                              (param => {
                                                                                                                return {
                                                                                                                  TAG: "ApproxThreshold",
                                                                                                                  _0: 0.001,
                                                                                                                  _1: 0.422,
                                                                                                                  _2: Math.tan(0.4)
                                                                                                                };
                                                                                                              })
                                                                                                            ],
                                                                                                            tl: {
                                                                                                              hd: [
                                                                                                                "tanh",
                                                                                                                (param => {
                                                                                                                  return {
                                                                                                                    TAG: "ApproxThreshold",
                                                                                                                    _0: 0.001,
                                                                                                                    _1: 0.379,
                                                                                                                    _2: Math.tanh(0.4)
                                                                                                                  };
                                                                                                                })
                                                                                                              ],
                                                                                                              tl: {
                                                                                                                hd: [
                                                                                                                  "unsafe_trunc",
                                                                                                                  (param => {
                                                                                                                    return {
                                                                                                                      TAG: "Eq",
                                                                                                                      _0: 4,
                                                                                                                      _1: Math.trunc(4.2156)
                                                                                                                    };
                                                                                                                  })
                                                                                                                ],
                                                                                                                tl: {
                                                                                                                  hd: [
                                                                                                                    "trunc",
                                                                                                                    (param => {
                                                                                                                      return {
                                                                                                                        TAG: "Eq",
                                                                                                                        _0: 4,
                                                                                                                        _1: Math.trunc(4.2156)
                                                                                                                      };
                                                                                                                    })
                                                                                                                  ],
                                                                                                                  tl: /* [] */0
                                                                                                                }
                                                                                                              }
                                                                                                            }
                                                                                                          }
                                                                                                        }
                                                                                                      }
                                                                                                    }
                                                                                                  }
                                                                                                }
                                                                                              }
                                                                                            }
                                                                                          }
                                                                                        }
                                                                                      }
                                                                                    }
                                                                                  }
                                                                                }
                                                                              }
                                                                            }
                                                                          }
                                                                        }
                                                                      }
                                                                    }
                                                                  }
                                                                }
                                                              }
                                                            }
                                                          }
                                                        }
                                                      }
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
};

let suites = {
  hd: suites_0,
  tl: suites_1
};

Mt.from_pair_suites("Js_math_test", suites);

exports.suites = suites;
/*  Not a pure module */
