// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let CamlinternalLazy = require("../../lib/js/camlinternalLazy.js");

let lazy1 = CamlinternalLazy.from_fun(() => {
  console.log("Hello, lazy");
  return 1;
});

let lazy2 = CamlinternalLazy.from_fun(() => 3);

console.log(lazy1, lazy2);

let la = CamlinternalLazy.force(lazy1);

let lb = CamlinternalLazy.force(lazy2);

console.log(la, lb);

exports.lazy1 = lazy1;
exports.lazy2 = lazy2;
exports.la = la;
exports.lb = lb;
/*  Not a pure module */
