// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function f() {
  throw new Error("Assert_failure", {
    cause: {
      RE_EXN_ID: "Assert_failure",
      _1: [
        "noassert.res",
        1,
        14
      ]
    }
  });
}

function h() {
  
}

exports.f = f;
exports.h = h;
/* No side effect */
