// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var SomeModule = require("SomeModule");

SomeModule.formatDate(new Date());

SomeModule.formatDate(new Date(), {
      someOption: true
    });

SomeModule.formatDate(new Date(), undefined, true);

var x = (42).toString();

exports.x = x;
/*  Not a pure module */
