export var dbg: any ;
export var inch: any ;
export var bufferize: (f : any) => any ;
export var getch: any ;
export var ungetch: any ;
export var peekch: (param : any) => any ;
export var addsym: any ;
export var symstr: any ;
export var symitr: any ;
export var glo: any ;
export var gpos: any ;
export var base: any ;
export var textoff: any ;
export var next: any ;
export var unnext: any ;
export var nextis: (t : any) => any ;
export var obuf: any ;
export var opos: any ;
export var out: (x : any) => any ;
export var le: (n : any, x : any) => any ;
export var get32: (l : any) => any ;
export var patch: (rel : any, loc : any, n : any) => any ;
export var load: (r : any, n : any) => any ;
export var cmp: (n : any) => any ;
export var test: (n : any, l : any) => any ;
export var align: any ;
export var push: (r : any) => any ;
export var pop: (r : any) => any ;
export var lval: any ;
export var patchlval: (param : any) => any ;
export var read: (param : any) => any ;
export var globs: any ;
export var lvls: any ;
export var inss: any ;
export var tokint: any ;
export var tokchar: any ;
export var tokret: any ;
export var tokif: any ;
export var tokelse: any ;
export var tokwhile: any ;
export var tokfor: any ;
export var tokbreak: any ;
export var binary: (stk : any, lvl : any) => any ;
export var unary: (stk : any) => any ;
export var postfix: (stk : any) => any ;
export var expr: (stk : any) => any ;
export var decl: (g : any, n : any, stk : any) => any ;
export var retl: any ;
export var stmt: (brk : any, stk : any) => any ;
export var block: (brk : any, stk : any) => any ;
export var top: (param : any) => any ;
export var elfhdr: any ;
export var elfphdr: (ty : any, off : any, sz : any, align : any) => any ;
export var elfgen: (outf : any) => any ;
export var main: (param : any) => any ;

