export var x: any ;
export var a: any ;
export var b: any ;
export var c: any ;
export var xx: any ;
export var naive: (n : any) => any ;
export var fib: (n : any) => any ;
export var xs: any ;
export var fib2: (n : any) => any ;
export var two: any ;
export var fib3: (n : any) => any ;
export var even: (n : any) => any ;
export var even2: (n : any) => any ;
export var lazy_v: (param : any) => any ;
export var sum: (acc : any, n : any) => any ;
export var fake_v: any ;
export var fake_y: any ;
export var fake_z: any ;
export var fake_z2: any ;
export var fake_y2: any ;
export var v: any ;
export var suites: any ;

