// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function getY(v) {
  return v.y;
}

function getX(v) {
  return v.x;
}

var v = {
  y: 3,
  x: 3
};

exports.getY = getY;
exports.getX = getX;
exports.v = v;
/* No side effect */
