// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Submodule = require("./submodule.js");

let a0 = Submodule.A0.a0(1, 2);

let a1 = Submodule.A0.A1.a1(1, 2);

let a2 = Submodule.A0.A1.A2.a2(1, 2);

let a3 = Submodule.A0.A1.A2.A3.a3(1, 2);

let a4 = Submodule.A0.A1.A2.A3.A4.a4(1, 2);

exports.a0 = a0;
exports.a1 = a1;
exports.a2 = a2;
exports.a3 = a3;
exports.a4 = a4;
/* a0 Not a pure module */
