// Generated CODE, PLEASE EDIT WITH CARE
"use strict";
var Pervasives = require("../stdlib/pervasives");
var List = require("../stdlib/list");

var $at = Pervasives.$at;

var Pervasives$1 = [
  0,
  List.length,
  List.hd,
  List.tl,
  List.nth,
  List.rev,
  List.append,
  List.rev_append,
  List.concat,
  List.flatten,
  List.iter,
  List.iteri,
  List.map,
  List.mapi,
  List.rev_map,
  List.fold_left,
  List.fold_right,
  List.iter2,
  List.map2,
  List.rev_map2,
  List.fold_left2,
  List.fold_right2,
  List.for_all,
  List.exists,
  List.for_all2,
  List.exists2,
  List.mem,
  List.memq,
  List.find,
  List.filter,
  List.find_all,
  List.partition,
  List.assoc,
  List.assq,
  List.mem_assoc,
  List.mem_assq,
  List.remove_assoc,
  List.remove_assq,
  List.split,
  List.combine,
  List.sort,
  List.stable_sort,
  List.fast_sort,
  List.sort_uniq,
  List.merge,
  Pervasives.invalid_arg,
  Pervasives.failwith,
  Pervasives.Exit,
  Pervasives.min,
  Pervasives.max,
  Pervasives.abs,
  Pervasives.max_int,
  Pervasives.min_int,
  Pervasives.lnot,
  Pervasives.infinity,
  Pervasives.neg_infinity,
  Pervasives.nan,
  Pervasives.max_float,
  Pervasives.min_float,
  Pervasives.epsilon_float,
  Pervasives.$caret,
  Pervasives.char_of_int,
  Pervasives.string_of_bool,
  Pervasives.bool_of_string,
  Pervasives.string_of_int,
  Pervasives.string_of_float,
  $at,
  Pervasives.stdin,
  Pervasives.stdout,
  Pervasives.stderr,
  Pervasives.print_char,
  Pervasives.print_string,
  Pervasives.print_bytes,
  Pervasives.print_int,
  Pervasives.print_float,
  Pervasives.print_endline,
  Pervasives.print_newline,
  Pervasives.prerr_char,
  Pervasives.prerr_string,
  Pervasives.prerr_bytes,
  Pervasives.prerr_int,
  Pervasives.prerr_float,
  Pervasives.prerr_endline,
  Pervasives.prerr_newline,
  Pervasives.read_line,
  Pervasives.read_int,
  Pervasives.read_float,
  Pervasives.open_out,
  Pervasives.open_out_bin,
  Pervasives.open_out_gen,
  Pervasives.flush,
  Pervasives.flush_all,
  Pervasives.output_char,
  Pervasives.output_string,
  Pervasives.output_bytes,
  Pervasives.output,
  Pervasives.output_substring,
  Pervasives.output_byte,
  Pervasives.output_binary_int,
  Pervasives.output_value,
  Pervasives.seek_out,
  Pervasives.pos_out,
  Pervasives.out_channel_length,
  Pervasives.close_out,
  Pervasives.close_out_noerr,
  Pervasives.set_binary_mode_out,
  Pervasives.open_in,
  Pervasives.open_in_bin,
  Pervasives.open_in_gen,
  Pervasives.input_char,
  Pervasives.input_line,
  Pervasives.input,
  Pervasives.really_input,
  Pervasives.really_input_string,
  Pervasives.input_byte,
  Pervasives.input_binary_int,
  Pervasives.input_value,
  Pervasives.seek_in,
  Pervasives.pos_in,
  Pervasives.in_channel_length,
  Pervasives.close_in,
  Pervasives.close_in_noerr,
  Pervasives.set_binary_mode_in,
  Pervasives.LargeFile,
  Pervasives.string_of_format,
  Pervasives.$caret$caret,
  Pervasives.exit,
  Pervasives.at_exit,
  Pervasives.valid_float_lexem,
  Pervasives.unsafe_really_input,
  Pervasives.do_at_exit
];

var f = $at;

exports.Pervasives = Pervasives$1;
exports.f = f;
/* No side effect */
