export var a0: any ;
export var a1: any ;
export var a2: any ;
export var a3: any ;
export var a4: (prim : any) => any ;
export var a5: (prim : any) => any ;
export var a6: (prim : any) => any ;
export var test_float: any ;
export var test_abs: any ;
export var v: any ;
export var xxx: any ;
export var a: any ;
export var u: (b : any) => any ;
export var f2: (h : any, b : any, param : any) => any ;
export var xx: any ;
export var unboxed_x: any ;
export var gg: (x : any) => any ;
export var f: (x : any) => any ;
export var is_lazy_force: (x : any) => any ;
export var fib: (n : any) => any ;

