// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Caml_js_exceptions = require("../../lib/js/caml_js_exceptions.js");

function f(x) {
  switch (x) {
    case "abcd" :
      return 0;
    case "bcde" :
      return 1;
    default:
      throw Caml_js_exceptions.internalFromExtension({
        RE_EXN_ID: "Assert_failure",
        _1: [
          "test_string_case.res",
          5,
          9
        ]
      });
  }
}

exports.f = f;
/* No side effect */
