export var failwith: (s : any) => any ;
export var invalid_arg: (s : any) => any ;
export var Exit: any ;
export var min: (x : any, y : any) => any ;
export var max: (x : any, y : any) => any ;
export var abs: (x : any) => any ;
export var lnot: (x : any) => any ;
export var max_int: any ;
export var min_int: any ;
export var infinity: any ;
export var neg_infinity: any ;
export var nan: any ;
export var max_float: any ;
export var min_float: any ;
export var epsilon_float: any ;
export var $caret: (s1 : any, s2 : any) => any ;
export var char_of_int: (n : any) => any ;
export var string_of_bool: (b : any) => any ;
export var bool_of_string: (param : any) => any ;
export var string_of_int: (n : any) => any ;
export var valid_float_lexem: (s : any) => any ;
export var string_of_float: (f : any) => any ;
export var $at: (l1 : any, l2 : any) => any ;
export var stdin: any ;
export var stdout: any ;
export var stderr: any ;
export var open_out_gen: (mode : any, perm : any, name : any) => any ;
export var open_out: (name : any) => any ;
export var open_out_bin: (name : any) => any ;
export var flush_all: (param : any) => any ;
export var output_bytes: (oc : any, s : any) => any ;
export var output_string: (oc : any, s : any) => any ;
export var output: (oc : any, s : any, ofs : any, len : any) => any ;
export var output_substring: (oc : any, s : any, ofs : any, len : any) => any
  ;
export var output_value: (chan : any, v : any) => any ;
export var close_out: (oc : any) => any ;
export var close_out_noerr: (oc : any) => any ;
export var open_in_gen: (mode : any, perm : any, name : any) => any ;
export var open_in: (name : any) => any ;
export var open_in_bin: (name : any) => any ;
export var input: (ic : any, s : any, ofs : any, len : any) => any ;
export var unsafe_really_input:
  (ic : any, s : any, ofs : any, len : any) => any ;
export var really_input: (ic : any, s : any, ofs : any, len : any) => any ;
export var really_input_string: (ic : any, len : any) => any ;
export var input_line: (chan : any) => any ;
export var close_in_noerr: (ic : any) => any ;
export var print_char: (c : any) => any ;
export var print_string: (s : any) => any ;
export var print_bytes: (s : any) => any ;
export var print_int: (i : any) => any ;
export var print_float: (f : any) => any ;
export var print_endline: (s : any) => any ;
export var print_newline: (param : any) => any ;
export var prerr_char: (c : any) => any ;
export var prerr_string: (s : any) => any ;
export var prerr_bytes: (s : any) => any ;
export var prerr_int: (i : any) => any ;
export var prerr_float: (f : any) => any ;
export var prerr_endline: (s : any) => any ;
export var prerr_newline: (param : any) => any ;
export var read_line: (param : any) => any ;
export var read_int: (param : any) => any ;
export var read_float: (param : any) => any ;
export var LargeFile: any ;
export var string_of_format: (param : any) => any ;
export var $caret$caret: (param : any, param : any) => any ;
export var exit_function: any ;
export var at_exit: (f : any) => any ;
export var do_at_exit: (param : any) => any ;
export var exit: (retcode : any) => any ;

