



;;; 1. we need a special string to mark vpath (reader macro)
;;; 2. checkout cl handles conditional compilation


(setq 
 bsc 
 "jscomp//bin/bsc.exe"
 bs-external-includes
 '( "jscomp/runtime" "jscomp/stdlib"  "jscomp/others")
 package-name
 "bs-platform")

(setq 
 bsc-flags '("-w" "-40" "-bs-no-version-header "  "-bs-cross-module-opt"))

(setq
 build-output-prefix "_build"
)
;; (setq a '(  '(a) )) 
;; (setq "gho" 3)
;; (setq x 3 y 2)
(setq 
 static-resources 
 '("jscomp/test/flow_parser_sample.js"
   "jscomp/test/joinClasses.js"
   ) )

(setq file-groups
      '(
        (
         (dir "jscomp/test/")
         (sources
          (
           hello_reason.re 
           hello_reason.rei
           hello_reason_dep.re
           
           a.ml
           a_filename_test.ml
           a_list_test.ml
           a_recursive_type.ml
           a_recursive_type.mli
           a_scope_bug.ml
           a_string_test.ml
           abstract_type.ml
           abstract_type.mli
           and_or_tailcall_test.ml
           ari_regress_test.ml
           ari_regress_test.mli
           arith_lexer.mll
           arith_parser.ml
           arith_syntax.ml
           array_subtle_test.ml
           array_test.ml
           array_test.mli
           attr_test.ml
           b.ml
           basic_module_test.ml
           basic_module_test.mli
           bdd.ml
           bench.ml
           bigarray_test.ml
           boolean_test.ml
           bs_array_test.ml
           bs_ignore_effect.ml
           bs_ignore_test.ml
           bs_node_string_buffer_test.ml
           bs_rest_test.ml
           bs_string_test.ml
           buffer_test.ml
           bytes_split_gpr_743_test.ml
           caml_compare_test.ml
           caml_format_test.ml
           chain_code_test.ml
           class3_test.ml
           class4_test.ml
           class5_test.ml
           class6_test.ml
           class7_test.ml
           class8_test.ml
           class_repr.ml
           class_setter_getter.ml
           class_setter_getter.mli
           class_test.ml
           class_type_ffi_test.ml
           complex_if_test.ml
           complex_test.ml
           complex_while_loop.ml
           condition_compilation_test.ml
           config1_test.ml
           config2_test.ml
           config2_test.mli
           const_block_test.ml
           const_block_test.mli
           const_defs.ml
           const_defs_test.ml
           const_test.ml
           cont_int_fold_test.ml
           cps_test.ml
           cross_module_inline_test.ml
           debug_keep_test.ml
           debugger_test.ml
           demo.ml
           demo_binding.ml
           demo_int_map.ml
           demo_int_map.mli
           demo_page.ml
           demo_pipe.ml
           derive_dyntype.ml
           derive_type_test.ml
           digest_test.ml
           div_by_zero_test.ml
           earger_curry_test.ml
           empty_obj.ml
           epsilon_test.ml
           equal_exception_test.ml
           equal_test.ml
           es6_module_test.ml
           event_ffi.ml
           exception_raise_test.ml
           exception_value_test.ml
           ext_array.ml
           ext_bytes.ml
           ext_filename.ml
           ext_list.ml
           ext_log.ml
           ext_pervasives.ml
           ext_pervasives.mli
           ext_string.ml
           ext_sys.ml
           ext_sys.mli
           extensible_variant_test.ml
           external_ppx.ml
           fail_comp.ml
           ffi_arity_test.ml
           ffi_array_test.ml
           ffi_js_test.ml
           ffi_splice_test.ml
           ffi_test.ml
           fib.ml
           float_array.ml
           float_of_bits_test.ml
           float_record.ml
           float_record.mli
           float_test.ml
           flow_parser_reg_test.ml
           flow_parser_reg_test.mli
           for_loop_test.ml
           for_side_effect_test.ml
           format_regression.ml
           format_test.ml
           fs_test.ml
           genlex_test.ml
           global_exception_regression_test.ml
           google_closure_test.ml
           gpr496_test.ml
           gpr_405_test.ml
           gpr_405_test.mli
           gpr_441.ml
           gpr_459_test.ml
           gpr_627_test.ml
           gpr_658.ml
           guide_for_ext.ml
           hamming_test.ml
           hash_test.ml
           hashtbl_test.ml
           hello.foo.ml
           http_types.ml
           ignore_test.ml
           infer_type_test.ml
           infer_type_test.mli
           inline_edge_cases.ml
           inline_edge_cases.mli
           inline_map2_test.ml
           inline_map_test.ml
           inline_map_test.mli
           inline_regression_test.ml
           inline_string_test.ml
           installation_test.ml
           int32_test.ml
           int64_mul_div_test.ml
           int64_test.ml
           int_hashtbl_test.ml
           int_map.ml
           int_overflow_test.ml
           io_test.ml
           js_bool_test.ml
           js_date.ml
           js_date_test.ml
           js_json_test.ml
           js_obj_test.ml
           js_string_test.ml
           js_val.ml
           jsoo_400_test.ml
           jsoo_485.ml
           jsoo_485_test.ml
           largest_int_flow.ml
           lazy_test.ml
           lexer_test.ml
           lib_js_test.ml
           libarg_test.ml
           libqueue_test.ml
           limits_test.ml
           list_test.ml
           literals.ml
           literals.mli
           local_class_type.ml
           local_exception_test.ml
           loop_regression_test.ml
           loop_suites_test.ml
           map_find_test.ml
           map_test.ml
           map_test.mli
           method_chain.ml
           method_name_test.ml
           mock_mt.ml
           module_alias.ml
           module_as_class_ffi.ml
           module_as_function.ml
           module_missing_conversion.ml
           module_parameter_test.ml
           module_splice_test.ml
           more_uncurry.ml
           mt.ml
           mt.mli
           mt_global.ml
           mt_global.mli
           mutable_obj_test.ml
           mutual_non_recursive_type.ml
           nested_include.ml
           nested_module_alias.ml
           nested_obj_literal.ml
           nested_obj_test.ml
           noassert.ml
           node_fs_test.ml
           node_path_test.ml
           number_lexer.mll
           obj_literal_ppx.ml
           obj_literal_ppx_test.ml
           obj_magic_test.ml
           obj_test.ml
           obj_type_test.ml
           ocaml_proto_test.ml
           ocaml_proto_test.mli
           of_string_test.ml
           offset.ml
           optional_ffi_test.ml
           pipe_send_readline.ml
           poly_type.ml
           poly_variant_test.ml
           poly_variant_test.mli
           polymorphism_test.ml
           polymorphism_test.mli
           polyvar_test.ml
           ppx_apply_test.ml
           ppx_this_obj_field.ml
           ppx_this_obj_test.ml
           pq_test.ml
           pr6726.ml
           pr_regression_test.ml
           primitive_reg_test.ml
           print_alpha_test.ml
           printf_sim.ml
           printf_test.ml
           promise.ml
           qcc.ml
           queue_test.ml
           random_test.ml
           rec_module_test.ml
           rec_value_test.ml
           record_with_test.ml
           recursive_module.ml
           recursive_module_test.ml
           regression_print.ml
           runtime_encoding_test.ml
           scanf_io.ml
           scanf_reference_error_regression_test.ml
           scanf_reference_error_regression_test.mli
           scanf_test.ml
           sexp.ml
           sexp.mli
           sexpm.ml
           sexpm.mli
           sexpm_test.ml
           shift_test.ml
           simple_derive_test.ml
           simple_derive_test.mli
           simple_derive_use.ml
           simple_derive_use.mli
           simple_lexer_test.mll
           simplify_lambda_632o.ml
           single_module_alias.ml
           small_inline_test.ml
           sprintf_reg_test.ml
           stack_comp_test.ml
           stack_test.ml
           stream_parser_test.ml
           string_bound_get_test.ml
           string_get_set_test.ml
           string_literal_print_test.ml
           string_runtime_test.ml
           string_test.ml
           string_unicode_test.ml
           stringmatch_test.ml
           swap_test.ml
           tailcall_inline_test.ml
           test_alias.ml
           test_ari.ml
           test_array.ml
           test_array_append.ml
           test_array_primitive.ml
           test_bool_equal.ml
           test_bs_this.ml
           test_bug.ml
           test_bytes.ml
           test_case_set.ml
           test_char.ml
           test_closure.ml
           test_common.ml
           test_const_elim.ml
           test_const_propogate.ml
           test_cps.ml
           test_demo.ml
           test_dup_param.ml
           test_eq.ml
           test_exception.ml
           test_exception_escape.ml
           test_export2.ml
           test_external.ml
           test_external_unit.ml
           test_ffi.ml
           test_fib.ml
           test_filename.ml
           test_for_loop.ml
           test_for_map.ml
           test_for_map2.ml
           test_for_map2.mli
           test_format.ml
           test_formatter.ml
           test_functor_dead_code.ml
           test_generative_module.ml
           test_global_print.ml
           test_google_closure.ml
           test_http_server.ml
           test_http_server.mli
           test_include.ml
           test_incomplete.ml
           test_incr_ref.ml
           test_index.ml
           test_int_map_find.ml
           test_internalOO.ml
           test_is_js.ml
           test_is_js.mli
           test_js_ffi.ml
           test_let.ml
           test_list.ml
           test_literal.ml
           test_match_exception.ml
           test_mutliple.ml
           test_nat64.ml
           test_nested_let.ml
           test_nested_print.ml
           test_non_export.ml
           test_nullary.ml
           test_obj.ml
           test_obj_simple_ffi.ml
           test_order.ml
           test_order_tailcall.ml
           test_pack.ml
           test_per.ml
           test_pervasive.ml
           test_pervasives2.ml
           test_pervasives3.ml
           test_primitive.ml
           test_ramification.ml
           test_react.ml
           test_react_case.ml
           test_regex.ml
           test_require.ml
           test_runtime_encoding.ml
           test_scope.ml
           test_seq.ml
           test_set.ml
           test_side_effect_functor.ml
           test_simple_include.ml
           test_simple_obj.ml
           test_simple_pattern_match.ml
           test_simple_ref.ml
           test_simple_tailcall.ml
           test_small.ml
           test_sprintf.ml
           test_stack.ml
           test_static_catch_ident.ml
           test_string.ml
           test_string_case.ml
           test_string_const.ml
           test_string_map.ml
           test_string_switch.ml
           test_switch.ml
           test_trywith.ml
           test_tuple.ml
           test_tuple_destructring.ml
           test_type_based_arity.ml
           test_u.ml
           test_unsafe_cmp.ml
           test_unsafe_obj_ffi.ml
           test_unsafe_obj_ffi.mli
           test_unsafe_obj_ffi_ppx.ml
           test_unsafe_obj_ffi_ppx.mli
           test_unsupported_primitive.ml
           test_while_closure.ml
           test_while_side_effect.ml
           test_zero_nullable.ml
           testing.ml
           testing.mli
           tfloat_record_test.ml
           ticker.ml
           to_string_test.ml
           tscanf_test.ml
           tuple_alloc.ml
           typeof_test.ml
           ui_defs.mli
           uncurry_glob_test.ml
           undef_regression_test.ml
           unitest_string.ml
           unsafe_obj_external.ml
           unsafe_ppx_test.ml
           unsafe_this.ml
           unsafe_this.mli
           update_record_test.ml
           utf8_decode_test.ml
           watch_test.ml
           app_root_finder.ml
           )))))




