#!/usr/bin/env node
"use strict";

var child_process = require("child_process");
var bsc_exe = require("./scripts/bin_path").bsc_exe;

var delegate_args = process.argv.slice(2);

try {
  child_process.execFileSync(bsc_exe, delegate_args, { stdio: "inherit" });
} catch (e) {
  if (e.code === "ENOENT") {
    console.error(String(e));
  }
  process.exit(2);
}
