#!/usr/bin/env node
"use strict";

var child_process = require("child_process");
var path = require("path");
var exe = path.join(__dirname, process.platform, "bsc.exe");
var delegate_args = process.argv.slice(2);

try {
  child_process.execFileSync(exe, delegate_args, { stdio: "inherit" });
} catch (e) {
  if (e.code === "ENOENT") {
    console.error(String(e));
  }
  process.exit(2);
}
