#!/usr/bin/env node
//@ts-check
"use strict";

var child_process = require("child_process");
var os = require("os");
var path = require("path");

var exe = path.join(__dirname, process.platform, "rescript.exe");
child_process.execFileSync(exe, process.argv.slice(2), { stdio: "inherit" });
