graph [
    comment "This is a sample graph"
    directed 1
    id 42
    label "Hello, I am a graph"
    node [ id 1 label "Node 1" ]
    node [ id 2 label "node 2" ]
    node [ id 3 label "node 3" ]
    node [ id 4 label "node 3" ]
    node [ id 5 label "node 3" ]
    node [ id 6 label "node 3" ]
    node [ id 7 label "node 3" ]
    node [ id 8 label "node 3" ]
    node [ id 9 label "node 3" ]
    node [ id 10 label "node 3" ]
    node [ id 11 label "node 3" ]
    node [ id 12 label "node 3" ]
    edge [ source 1 target 2 ]
    edge [ source 1 target 4 ]
    edge [ source 1 target 5 ]
    edge [ source 1 target 6 ]
    edge [ source 1 target 7 ]
    edge [ source 2 target 7 ]
    edge [ source 3 target 7 ]
    edge [ source 1 target 8 ]
    edge [ source 2 target 3 ]
    edge [ source 3 target 1 ]
    edge [ source 8 target 9 ]
    edge [ source 8 target 10 ]
    edge [ source 8 target 11 ]
    edge [ source 8 target 12 ]
]