// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function OnClick2(Props) {
  let onClick = Props.onClick;
  return React.createElement("div", {
    onClick: onClick
  });
}

let make = OnClick2;

export {
  make,
}
/* react Not a pure module */
