
CAMLDEP=ocamldep.opt
CAMLLEX=ocamllex.opt
CAMLOPT=ocamlopt.opt




.SUFFIXES: .mli .ml .cmi .cmo .cmx .p.cmx .cmj .js


ifdef BS_RELEASE_BUILD
BS_PKG_FLAGS=  -nostdlib -bs-package-output commonjs:lib/js -bs-package-output amdjs:lib/amdjs -bs-package-output es6:lib/es6
else
BS_PKG_FLAGS=  -nostdlib -bs-package-output commonjs:lib/js -bs-package-output es6:lib/es6
endif

print-%  : ; @echo $* = $($*)