/* Copyright (C) 2015-2016 Bloomberg Finance L.P.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * In addition to the permissions granted to you by the LGPL, you may combine
 * or link a "work that uses the Library" with a publicly distributed version
 * of this file to produce a combined library or application, then distribute
 * that combined work under the terms of your choosing, with no requirement
 * to comply with the obligations normally placed on you by section 4 of the
 * LGPL version 3 (or the corresponding section of a later version of the LGPL
 * should you choose to use a later version).
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA. */

type t = {
  accentColor?: string,
  alignContent?: string,
  alignItems?: string,
  alignSelf?: string,
  all?: string,
  animation?: string,
  animationComposition?: string,
  animationDelay?: string,
  animationDirection?: string,
  animationDuration?: string,
  animationFillMode?: string,
  animationIterationCount?: string,
  animationName?: string,
  animationPlayState?: string,
  animationTimingFunction?: string,
  appearance?: string,
  aspectRatio?: string,
  backdropFilter?: string,
  backfaceVisibility?: string,
  background?: string,
  backgroundAttachment?: string,
  backgroundBlendMode?: string,
  backgroundClip?: string,
  backgroundColor?: string,
  backgroundImage?: string,
  backgroundOrigin?: string,
  backgroundPosition?: string,
  backgroundPositionX?: string,
  backgroundPositionY?: string,
  backgroundRepeat?: string,
  backgroundSize?: string,
  blockSize?: string,
  border?: string,
  borderBlock?: string,
  borderBlockColor?: string,
  borderBlockEnd?: string,
  borderBlockEndColor?: string,
  borderBlockEndStyle?: string,
  borderBlockEndWidth?: string,
  borderBlockStart?: string,
  borderBlockStartColor?: string,
  borderBlockStartStyle?: string,
  borderBlockStartWidth?: string,
  borderBlockStyle?: string,
  borderBlockWidth?: string,
  borderBottom?: string,
  borderBottomColor?: string,
  borderBottomLeftRadius?: string,
  borderBottomRightRadius?: string,
  borderBottomStyle?: string,
  borderBottomWidth?: string,
  borderCollapse?: string,
  borderColor?: string,
  borderEndEndRadius?: string,
  borderEndStartRadius?: string,
  borderImage?: string,
  borderImageOutset?: string,
  borderImageRepeat?: string,
  borderImageSlice?: string,
  borderImageSource?: string,
  borderImageWidth?: string,
  borderInline?: string,
  borderInlineColor?: string,
  borderInlineEnd?: string,
  borderInlineEndColor?: string,
  borderInlineEndStyle?: string,
  borderInlineEndWidth?: string,
  borderInlineStart?: string,
  borderInlineStartColor?: string,
  borderInlineStartStyle?: string,
  borderInlineStartWidth?: string,
  borderInlineStyle?: string,
  borderInlineWidth?: string,
  borderLeft?: string,
  borderLeftColor?: string,
  borderLeftStyle?: string,
  borderLeftWidth?: string,
  borderRadius?: string,
  borderRight?: string,
  borderRightColor?: string,
  borderRightStyle?: string,
  borderRightWidth?: string,
  borderSpacing?: string,
  borderStartEndRadius?: string,
  borderStartStartRadius?: string,
  borderStyle?: string,
  borderTop?: string,
  borderTopColor?: string,
  borderTopLeftRadius?: string,
  borderTopRightRadius?: string,
  borderTopStyle?: string,
  borderTopWidth?: string,
  borderWidth?: string,
  bottom?: string,
  boxDecorationBreak?: string,
  boxShadow?: string,
  boxSizing?: string,
  breakAfter?: string,
  breakBefore?: string,
  breakInside?: string,
  captionSide?: string,
  caret?: string,
  caretColor?: string,
  caretShape?: string,
  clear?: string,
  clipPath?: string,
  clipRule?: string,
  color?: string,
  colorInterpolationFilters?: string,
  colorScheme?: string,
  columnCount?: string,
  columnFill?: string,
  columnGap?: string,
  columnRule?: string,
  columnRuleColor?: string,
  columnRuleStyle?: string,
  columnRuleWidth?: string,
  columnSpan?: string,
  columnWidth?: string,
  columns?: string,
  contain?: string,
  containIntrinsicBlockSize?: string,
  containIntrinsicHeight?: string,
  containIntrinsicInlineSize?: string,
  containIntrinsicSize?: string,
  containIntrinsicWidth?: string,
  container?: string,
  containerName?: string,
  containerType?: string,
  content?: string,
  contentVisibility?: string,
  counterIncrement?: string,
  counterReset?: string,
  counterSet?: string,
  cursor?: string,
  cx?: string,
  cy?: string,
  d?: string,
  direction?: string,
  display?: string,
  dominantBaseline?: string,
  emptyCells?: string,
  fill?: string,
  fillOpacity?: string,
  fillRule?: string,
  filter?: string,
  flex?: string,
  flexBasis?: string,
  flexDirection?: string,
  flexFlow?: string,
  flexGrow?: string,
  flexShrink?: string,
  flexWrap?: string,
  float?: string,
  floodColor?: string,
  floodOpacity?: string,
  font?: string,
  fontFamily?: string,
  fontFeatureSettings?: string,
  fontKerning?: string,
  fontLanguageOverride?: string,
  fontOpticalSizing?: string,
  fontPalette?: string,
  fontSize?: string,
  fontSizeAdjust?: string,
  fontStretch?: string,
  fontStyle?: string,
  fontSynthesis?: string,
  fontSynthesisSmallCaps?: string,
  fontSynthesisStyle?: string,
  fontSynthesisWeight?: string,
  fontVariant?: string,
  fontVariantAlternates?: string,
  fontVariantCaps?: string,
  fontVariantEastAsian?: string,
  fontVariantEmoji?: string,
  fontVariantLigatures?: string,
  fontVariantNumeric?: string,
  fontVariantPosition?: string,
  fontVariationSettings?: string,
  fontWeight?: string,
  forcedColorAdjust?: string,
  gap?: string,
  grid?: string,
  gridArea?: string,
  gridAutoColumns?: string,
  gridAutoFlow?: string,
  gridAutoRows?: string,
  gridColumn?: string,
  gridColumnEnd?: string,
  gridColumnStart?: string,
  gridRow?: string,
  gridRowEnd?: string,
  gridRowStart?: string,
  gridTemplate?: string,
  gridTemplateAreas?: string,
  gridTemplateColumns?: string,
  gridTemplateRows?: string,
  hangingPunctuation?: string,
  height?: string,
  hyphenateCharacter?: string,
  hyphenateLimitChars?: string,
  hyphens?: string,
  imageOrientation?: string,
  imageRendering?: string,
  initialLetter?: string,
  inlineSize?: string,
  inputSecurity?: string,
  inset?: string,
  insetBlock?: string,
  insetBlockEnd?: string,
  insetBlockStart?: string,
  insetInline?: string,
  insetInlineEnd?: string,
  insetInlineStart?: string,
  isolation?: string,
  justifyContent?: string,
  justifyItems?: string,
  justifySelf?: string,
  left?: string,
  letterSpacing?: string,
  lightingColor?: string,
  lineBreak?: string,
  lineClamp?: string,
  lineHeight?: string,
  listStyle?: string,
  listStyleImage?: string,
  listStylePosition?: string,
  listStyleType?: string,
  margin?: string,
  marginBlock?: string,
  marginBlockEnd?: string,
  marginBlockStart?: string,
  marginBottom?: string,
  marginInline?: string,
  marginInlineEnd?: string,
  marginInlineStart?: string,
  marginLeft?: string,
  marginRight?: string,
  marginTop?: string,
  marker?: string,
  markerEnd?: string,
  markerMid?: string,
  markerStart?: string,
  mask?: string,
  maskBorder?: string,
  maskBorderMode?: string,
  maskBorderOutset?: string,
  maskBorderRepeat?: string,
  maskBorderSlice?: string,
  maskBorderSource?: string,
  maskBorderWidth?: string,
  maskClip?: string,
  maskComposite?: string,
  maskImage?: string,
  maskMode?: string,
  maskOrigin?: string,
  maskPosition?: string,
  maskRepeat?: string,
  maskSize?: string,
  maskType?: string,
  mathDepth?: string,
  mathStyle?: string,
  maxBlockSize?: string,
  maxHeight?: string,
  maxInlineSize?: string,
  maxWidth?: string,
  minBlockSize?: string,
  minHeight?: string,
  minInlineSize?: string,
  minWidth?: string,
  mixBlendMode?: string,
  objectFit?: string,
  objectPosition?: string,
  offset?: string,
  offsetAnchor?: string,
  offsetDistance?: string,
  offsetPath?: string,
  offsetPosition?: string,
  offsetRotate?: string,
  opacity?: string,
  order?: string,
  orphans?: string,
  outline?: string,
  outlineColor?: string,
  outlineOffset?: string,
  outlineStyle?: string,
  outlineWidth?: string,
  overflow?: string,
  overflowAnchor?: string,
  overflowBlock?: string,
  overflowClipMargin?: string,
  overflowInline?: string,
  overflowWrap?: string,
  overflowX?: string,
  overflowY?: string,
  overscrollBehavior?: string,
  overscrollBehaviorBlock?: string,
  overscrollBehaviorInline?: string,
  overscrollBehaviorX?: string,
  overscrollBehaviorY?: string,
  padding?: string,
  paddingBlock?: string,
  paddingBlockEnd?: string,
  paddingBlockStart?: string,
  paddingBottom?: string,
  paddingInline?: string,
  paddingInlineEnd?: string,
  paddingInlineStart?: string,
  paddingLeft?: string,
  paddingRight?: string,
  paddingTop?: string,
  page?: string,
  pageBreakAfter?: string,
  pageBreakBefore?: string,
  pageBreakInside?: string,
  paintOrder?: string,
  perspective?: string,
  perspectiveOrigin?: string,
  placeContent?: string,
  placeItems?: string,
  placeSelf?: string,
  pointerEvents?: string,
  position?: string,
  printColorAdjust?: string,
  quotes?: string,
  r?: string,
  resize?: string,
  right?: string,
  rotate?: string,
  rowGap?: string,
  rubyAlign?: string,
  rubyPosition?: string,
  rx?: string,
  ry?: string,
  scale?: string,
  scrollBehavior?: string,
  scrollMargin?: string,
  scrollMarginBlock?: string,
  scrollMarginBlockEnd?: string,
  scrollMarginBlockStart?: string,
  scrollMarginBottom?: string,
  scrollMarginInline?: string,
  scrollMarginInlineEnd?: string,
  scrollMarginInlineStart?: string,
  scrollMarginLeft?: string,
  scrollMarginRight?: string,
  scrollMarginTop?: string,
  scrollPadding?: string,
  scrollPaddingBlock?: string,
  scrollPaddingBlockEnd?: string,
  scrollPaddingBlockStart?: string,
  scrollPaddingBottom?: string,
  scrollPaddingInline?: string,
  scrollPaddingInlineEnd?: string,
  scrollPaddingInlineStart?: string,
  scrollPaddingLeft?: string,
  scrollPaddingRight?: string,
  scrollPaddingTop?: string,
  scrollSnapAlign?: string,
  scrollSnapStop?: string,
  scrollSnapType?: string,
  scrollbarColor?: string,
  scrollbarGutter?: string,
  scrollbarWidth?: string,
  shapeImageThreshold?: string,
  shapeMargin?: string,
  shapeOutside?: string,
  shapeRendering?: string,
  stopColor?: string,
  stopOpacity?: string,
  stroke?: string,
  strokeDasharray?: string,
  strokeDashoffset?: string,
  strokeLinecap?: string,
  strokeLinejoin?: string,
  strokeMiterlimit?: string,
  strokeOpacity?: string,
  strokeWidth?: string,
  tabSize?: string,
  tableLayout?: string,
  textAlign?: string,
  textAlignLast?: string,
  textAnchor?: string,
  textCombineUpright?: string,
  textDecoration?: string,
  textDecorationColor?: string,
  textDecorationLine?: string,
  textDecorationSkipInk?: string,
  textDecorationStyle?: string,
  textDecorationThickness?: string,
  textEmphasis?: string,
  textEmphasisColor?: string,
  textEmphasisPosition?: string,
  textEmphasisStyle?: string,
  textIndent?: string,
  textJustify?: string,
  textOrientation?: string,
  textOverflow?: string,
  textRendering?: string,
  textShadow?: string,
  textTransform?: string,
  textUnderlineOffset?: string,
  textUnderlinePosition?: string,
  textWrap?: string,
  textWrapMode?: string,
  textWrapStyle?: string,
  top?: string,
  touchAction?: string,
  transform?: string,
  transformBox?: string,
  transformOrigin?: string,
  transformStyle?: string,
  transition?: string,
  transitionBehavior?: string,
  transitionDelay?: string,
  transitionDuration?: string,
  transitionProperty?: string,
  transitionTimingFunction?: string,
  translate?: string,
  unicodeBidi?: string,
  userSelect?: string,
  vectorEffect?: string,
  verticalAlign?: string,
  viewTransitionName?: string,
  visibility?: string,
  whiteSpace?: string,
  whiteSpaceCollapse?: string,
  widows?: string,
  width?: string,
  willChange?: string,
  wordBreak?: string,
  wordSpacing?: string,
  wordWrap?: string,
  writingMode?: string,
  x?: string,
  y?: string,
  zIndex?: string,
  zoom?: string,

  /* Non-standard properties, for compatibility */
  @deprecated
  azimuth?: string,
  @deprecated
  clip?: string,
  @deprecated
  cue?: string,
  @deprecated
  cueAfter?: string,
  @deprecated
  cueBefore?: string,
  @deprecated
  elevation?: string,
  @deprecated
  markerOffset?: string,
  @deprecated
  marks?: string,
  @deprecated
  pause?: string,
  @deprecated
  pauseAfter?: string,
  @deprecated
  pauseBefore?: string,
  @deprecated
  pitch?: string,
  @deprecated
  pitchRange?: string,
  @deprecated
  playDuring?: string,
  @deprecated
  richness?: string,
  @deprecated
  size?: string,
  @deprecated
  speak?: string,
  @deprecated
  speakHeader?: string,
  @deprecated
  speakNumeral?: string,
  @deprecated
  speakPunctuation?: string,
  @deprecated
  speechRate?: string,
  @deprecated
  stress?: string,
  @deprecated
  voiceFamily?: string,
  @deprecated
  volume?: string,
  @deprecated
  rest?: string,
  @deprecated
  restAfter?: string,
  @deprecated
  restBefore?: string,
  @deprecated
  speakAs?: string,
  @deprecated
  voiceBalance?: string,
  @deprecated
  voiceDuration?: string,
  @deprecated
  voicePitch?: string,
  @deprecated
  voiceRange?: string,
  @deprecated
  voiceRate?: string,
  @deprecated
  voiceStress?: string,
  @deprecated
  voiceVolume?: string,
  @deprecated
  imageResolution?: string,
  @deprecated
  textDecorationSkip?: string,
  @deprecated
  forntVariantAlternates?: string,
  @deprecated
  glyphOrientationVertical?: string,
  @deprecated
  navDown?: string,
  @deprecated
  navLeft?: string,
  @deprecated
  navRight?: string,
  @deprecated
  navUp?: string,
  @deprecated
  gridColumnGap?: string,
  @deprecated
  gridGap?: string,
  @deprecated
  gridRowGap?: string,
  @deprecated
  caretAnimation?: string,
  @deprecated
  maxLines?: string,
  @deprecated
  marqueeDirection?: string,
  @deprecated
  marqueeLoop?: string,
  @deprecated
  marqueeSpeed?: string,
  @deprecated
  marqueeStyle?: string,
  @deprecated
  overflowStyle?: string,
  @deprecated
  rotation?: string,
  @deprecated
  rotationPoint?: string,
  @deprecated
  alignmentBaseline?: string,
  @deprecated
  baselineShift?: string,
  @deprecated
  colorInterpolation?: string,
  @deprecated
  colorProfile?: string,
  @deprecated
  colorRendering?: string,
  @deprecated
  glyphOrientationHorizontal?: string,
  @deprecated
  kerning?: string,
  @deprecated
  rubyMerge?: string,
}
