#!/usr/bin/env node
//@ts-check
"use strict";

const path = require("path");
const child_process = require("child_process");

const { absolutePath: binAbsolutePath } = require("./bin_path");
const rewatchExe = path.join(binAbsolutePath, "rescript-tools.exe");

const args = process.argv.slice(2);

child_process.spawnSync(rewatchExe, args, { stdio: "inherit" });
