export var open_box: (indent : any) => any ;
export var close_box: (param : any) => any ;
export var print_string: (s : any) => any ;
export var print_as: (isize : any, s : any) => any ;
export var print_int: (i : any) => any ;
export var print_float: (f : any) => any ;
export var print_char: (c : any) => any ;
export var print_bool: (b : any) => any ;
export var print_space: (param : any) => any ;
export var print_cut: (param : any) => any ;
export var print_break: (width : any, offset : any) => any ;
export var print_flush: (param : any) => any ;
export var print_newline: (param : any) => any ;
export var force_newline: (param : any) => any ;
export var print_if_newline: (param : any) => any ;
export var set_margin: (n : any) => any ;
export var get_margin: (param : any) => any ;
export var set_max_indent: (n : any) => any ;
export var get_max_indent: (param : any) => any ;
export var set_max_boxes: (n : any) => any ;
export var get_max_boxes: (param : any) => any ;
export var over_max_boxes: (param : any) => any ;
export var open_hbox: (param : any) => any ;
export var open_vbox: (indent : any) => any ;
export var open_hvbox: (indent : any) => any ;
export var open_hovbox: (indent : any) => any ;
export var open_tbox: (param : any) => any ;
export var close_tbox: (param : any) => any ;
export var print_tbreak: (width : any, offset : any) => any ;
export var set_tab: (param : any) => any ;
export var print_tab: (param : any) => any ;
export var set_ellipsis_text: (s : any) => any ;
export var get_ellipsis_text: (param : any) => any ;
export var open_tag: (tag_name : any) => any ;
export var close_tag: (param : any) => any ;
export var set_tags: (b : any) => any ;
export var set_print_tags: (b : any) => any ;
export var set_mark_tags: (b : any) => any ;
export var get_print_tags: (param : any) => any ;
export var get_mark_tags: (param : any) => any ;
export var set_formatter_out_channel: (os : any) => any ;
export var set_formatter_output_functions: (f : any, g : any) => any ;
export var get_formatter_output_functions: (param : any) => any ;
export var set_formatter_out_functions: (param : any) => any ;
export var get_formatter_out_functions: (param : any) => any ;
export var set_formatter_tag_functions: (param : any) => any ;
export var get_formatter_tag_functions: (param : any) => any ;
export var formatter_of_out_channel: (oc : any) => any ;
export var std_formatter: any ;
export var err_formatter: any ;
export var formatter_of_buffer: (b : any) => any ;
export var stdbuf: any ;
export var str_formatter: any ;
export var flush_str_formatter: (param : any) => any ;
export var make_formatter: (output : any, flush : any) => any ;
export var pp_open_hbox: (state : any, param : any) => any ;
export var pp_open_vbox: (state : any, indent : any) => any ;
export var pp_open_hvbox: (state : any, indent : any) => any ;
export var pp_open_hovbox: (state : any, indent : any) => any ;
export var pp_open_box: (state : any, indent : any) => any ;
export var pp_close_box: (state : any, param : any) => any ;
export var pp_open_tag: (state : any, tag_name : any) => any ;
export var pp_close_tag: (state : any, param : any) => any ;
export var pp_print_string: (state : any, s : any) => any ;
export var pp_print_as: (state : any, isize : any, s : any) => any ;
export var pp_print_int: (state : any, i : any) => any ;
export var pp_print_float: (state : any, f : any) => any ;
export var pp_print_char: (state : any, c : any) => any ;
export var pp_print_bool: (state : any, b : any) => any ;
export var pp_print_break: (state : any, width : any, offset : any) => any ;
export var pp_print_cut: (state : any, param : any) => any ;
export var pp_print_space: (state : any, param : any) => any ;
export var pp_force_newline: (state : any, param : any) => any ;
export var pp_print_flush: (state : any, param : any) => any ;
export var pp_print_newline: (state : any, param : any) => any ;
export var pp_print_if_newline: (state : any, param : any) => any ;
export var pp_open_tbox: (state : any, param : any) => any ;
export var pp_close_tbox: (state : any, param : any) => any ;
export var pp_print_tbreak: (state : any, width : any, offset : any) => any ;
export var pp_set_tab: (state : any, param : any) => any ;
export var pp_print_tab: (state : any, param : any) => any ;
export var pp_set_tags: (state : any, b : any) => any ;
export var pp_set_print_tags: (state : any, b : any) => any ;
export var pp_set_mark_tags: (state : any, b : any) => any ;
export var pp_get_print_tags: (state : any, param : any) => any ;
export var pp_get_mark_tags: (state : any, param : any) => any ;
export var pp_set_margin: (state : any, n : any) => any ;
export var pp_get_margin: (state : any, param : any) => any ;
export var pp_set_max_indent: (state : any, n : any) => any ;
export var pp_get_max_indent: (state : any, param : any) => any ;
export var pp_set_max_boxes: (state : any, n : any) => any ;
export var pp_get_max_boxes: (state : any, param : any) => any ;
export var pp_over_max_boxes: (state : any, param : any) => any ;
export var pp_set_ellipsis_text: (state : any, s : any) => any ;
export var pp_get_ellipsis_text: (state : any, param : any) => any ;
export var pp_set_formatter_out_channel: (state : any, os : any) => any ;
export var pp_set_formatter_output_functions:
  (state : any, f : any, g : any) => any ;
export var pp_get_formatter_output_functions:
  (state : any, param : any) => any ;
export var pp_set_formatter_tag_functions: (state : any, param : any) => any
  ;
export var pp_get_formatter_tag_functions: (state : any, param : any) => any
  ;
export var pp_set_formatter_out_functions: (state : any, param : any) => any
  ;
export var pp_get_formatter_out_functions: (state : any, param : any) => any
  ;
export var pp_print_list:
  ($staropt$star : any, pp_v : any, ppf : any, param : any) => any ;
export var pp_print_text: (ppf : any, s : any) => any ;
export var fprintf: (ppf : any, fmt : any) => any ;
export var printf: (fmt : any) => any ;
export var eprintf: (fmt : any) => any ;
export var sprintf: (fmt : any) => any ;
export var asprintf: (param : any) => any ;
export var ifprintf: (ppf : any, fmt : any) => any ;
export var kfprintf: (k : any, o : any, param : any) => any ;
export var ikfprintf: (k : any, x : any, param : any) => any ;
export var ksprintf: (k : any, param : any) => any ;
export var bprintf: (b : any, param : any) => any ;
export var kprintf: (k : any, param : any) => any ;
export var set_all_formatter_output_functions:
  (f : any, g : any, h : any, i : any) => any ;
export var get_all_formatter_output_functions: (param : any) => any ;
export var pp_set_all_formatter_output_functions:
  (state : any, f : any, g : any, h : any, i : any) => any ;
export var pp_get_all_formatter_output_functions:
  (state : any, param : any) => any ;

