export var create: ($staropt$star : any, initial_size : any) => any ;
export var clear: (h : any) => any ;
export var reset: (h : any) => any ;
export var copy: (h : any) => any ;
export var add: (h : any, key : any, info : any) => any ;
export var find: (h : any, key : any) => any ;
export var find_all: (h : any, key : any) => any ;
export var mem: (h : any, key : any) => any ;
export var remove: (h : any, key : any) => any ;
export var replace: (h : any, key : any, info : any) => any ;
export var iter: (f : any, h : any) => any ;
export var fold: (f : any, h : any, init : any) => any ;
export var length: (h : any) => any ;
export var randomize: (param : any) => any ;
export var stats: (h : any) => any ;
export var Make: (H : any) => any ;
export var MakeSeeded: (H : any) => any ;
export var hash: (x : any) => any ;
export var seeded_hash: (seed : any, x : any) => any ;
export var hash_param: (n1 : any, n2 : any, x : any) => any ;
export var seeded_hash_param: any ;

