export var double_field: (x : any, i : any) => any ;
export var set_double_field: (x : any, i : any, v : any) => any ;
export var first_non_constant_constructor_tag: any ;
export var last_non_constant_constructor_tag: any ;
export var lazy_tag: any ;
export var closure_tag: any ;
export var object_tag: any ;
export var infix_tag: any ;
export var forward_tag: any ;
export var no_scan_tag: any ;
export var abstract_tag: any ;
export var string_tag: any ;
export var double_tag: any ;
export var double_array_tag: any ;
export var custom_tag: any ;
export var final_tag: any ;
export var int_tag: any ;
export var out_of_heap_tag: any ;
export var unaligned_tag: any ;
export var extension_name: (x : any) => any ;
export var extension_id: (x : any) => any ;
export var extension_slot: (x : any) => any ;
export var marshal: (obj : any) => any ;
export var unmarshal: (str : any, pos : any) => any ;

