export var to_string: (x : any) => any ;
export var print: (fct : any, arg : any) => any ;
export var $$catch: (fct : any, arg : any) => any ;
export var print_backtrace: (outchan : any) => any ;
export var get_backtrace: (param : any) => any ;
export var record_backtrace: any ;
export var backtrace_status: any ;
export var register_printer: (fn : any) => any ;
export var get_raw_backtrace: any ;
export var print_raw_backtrace: (outchan : any, raw_backtrace : any) => any ;
export var raw_backtrace_to_string: (raw_backtrace : any) => any ;
export var get_callstack: any ;
export var set_uncaught_exception_handler: (fn : any) => any ;
export var backtrace_slots: (raw_backtrace : any) => any ;
export var Slot: any ;
export var raw_backtrace_length: (bckt : any) => any ;
export var get_raw_backtrace_slot: (bckt : any, i : any) => any ;
export var convert_raw_backtrace_slot: any ;
export var exn_slot_id: (x : any) => any ;
export var exn_slot_name: (x : any) => any ;

