export var argv: any ;
export var executable_name: any ;
export var interactive: any ;
export var os_type: any ;
export var unix: any ;
export var win32: any ;
export var cygwin: any ;
export var word_size: any ;
export var big_endian: any ;
export var is_js: any ;
export var max_string_length: any ;
export var max_array_length: any ;
export var set_signal: (sig_num : any, sig_beh : any) => any ;
export var sigabrt: any ;
export var sigalrm: any ;
export var sigfpe: any ;
export var sighup: any ;
export var sigill: any ;
export var sigint: any ;
export var sigkill: any ;
export var sigpipe: any ;
export var sigquit: any ;
export var sigsegv: any ;
export var sigterm: any ;
export var sigusr1: any ;
export var sigusr2: any ;
export var sigchld: any ;
export var sigcont: any ;
export var sigstop: any ;
export var sigtstp: any ;
export var sigttin: any ;
export var sigttou: any ;
export var sigvtalrm: any ;
export var sigprof: any ;
export var Break: any ;
export var catch_break: (on : any) => any ;
export var ocaml_version: any ;

