export var Unix_error: any ;
export var error_message: any ;
export var handle_unix_error: (f : any, arg : any) => any ;
export var environment: any ;
export var getenv: any ;
export var putenv: any ;
export var execv: any ;
export var execve: any ;
export var execvp: any ;
export var execvpe: any ;
export var fork: any ;
export var wait: any ;
export var waitpid: any ;
export var system: (cmd : any) => any ;
export var getpid: any ;
export var getppid: any ;
export var nice: any ;
export var stdin: any ;
export var stdout: any ;
export var stderr: any ;
export var openfile: any ;
export var close: any ;
export var read: (fd : any, buf : any, ofs : any, len : any) => any ;
export var write: (fd : any, buf : any, ofs : any, len : any) => any ;
export var single_write: (fd : any, buf : any, ofs : any, len : any) => any ;
export var write_substring:
  (fd : any, buf : any, ofs : any, len : any) => any ;
export var single_write_substring:
  (fd : any, buf : any, ofs : any, len : any) => any ;
export var in_channel_of_descr: any ;
export var out_channel_of_descr: any ;
export var descr_of_in_channel: any ;
export var descr_of_out_channel: any ;
export var lseek: any ;
export var truncate: any ;
export var ftruncate: any ;
export var stat: any ;
export var lstat: any ;
export var fstat: any ;
export var isatty: any ;
export var LargeFile: any ;
export var unlink: any ;
export var rename: any ;
export var link: any ;
export var chmod: any ;
export var fchmod: any ;
export var chown: any ;
export var fchown: any ;
export var umask: any ;
export var access: any ;
export var dup: any ;
export var dup2: any ;
export var set_nonblock: any ;
export var clear_nonblock: any ;
export var set_close_on_exec: any ;
export var clear_close_on_exec: any ;
export var mkdir: any ;
export var rmdir: any ;
export var chdir: any ;
export var getcwd: any ;
export var chroot: any ;
export var opendir: any ;
export var readdir: any ;
export var rewinddir: any ;
export var closedir: any ;
export var pipe: any ;
export var mkfifo: any ;
export var create_process:
  (cmd : any, args : any, new_stdin : any, new_stdout : any,
  new_stderr : any) => any ;
export var create_process_env:
  (cmd : any, args : any, env : any, new_stdin : any, new_stdout : any,
  new_stderr : any) => any ;
export var open_process_in: (cmd : any) => any ;
export var open_process_out: (cmd : any) => any ;
export var open_process: (cmd : any) => any ;
export var open_process_full: (cmd : any, env : any) => any ;
export var close_process_in: (inchan : any) => any ;
export var close_process_out: (outchan : any) => any ;
export var close_process: (param : any) => any ;
export var close_process_full: (param : any) => any ;
export var symlink: any ;
export var readlink: any ;
export var select: any ;
export var lockf: any ;
export var kill: any ;
export var sigprocmask: any ;
export var sigpending: any ;
export var sigsuspend: any ;
export var pause: (param : any) => any ;
export var time: any ;
export var gettimeofday: any ;
export var gmtime: any ;
export var localtime: any ;
export var mktime: any ;
export var alarm: any ;
export var sleep: any ;
export var times: any ;
export var utimes: any ;
export var getitimer: any ;
export var setitimer: any ;
export var getuid: any ;
export var geteuid: any ;
export var setuid: any ;
export var getgid: any ;
export var getegid: any ;
export var setgid: any ;
export var getgroups: any ;
export var setgroups: any ;
export var initgroups: any ;
export var getlogin: any ;
export var getpwnam: any ;
export var getgrnam: any ;
export var getpwuid: any ;
export var getgrgid: any ;
export var inet_addr_of_string: any ;
export var string_of_inet_addr: any ;
export var inet_addr_any: any ;
export var inet_addr_loopback: any ;
export var inet6_addr_any: any ;
export var inet6_addr_loopback: any ;
export var socket: any ;
export var domain_of_sockaddr: (param : any) => any ;
export var socketpair: any ;
export var accept: any ;
export var bind: any ;
export var connect: any ;
export var listen: any ;
export var shutdown: any ;
export var getsockname: any ;
export var getpeername: any ;
export var recv:
  (fd : any, buf : any, ofs : any, len : any, flags : any) => any ;
export var recvfrom:
  (fd : any, buf : any, ofs : any, len : any, flags : any) => any ;
export var send:
  (fd : any, buf : any, ofs : any, len : any, flags : any) => any ;
export var send_substring:
  (fd : any, buf : any, ofs : any, len : any, flags : any) => any ;
export var sendto:
  (fd : any, buf : any, ofs : any, len : any, flags : any, addr : any) => any
  ;
export var sendto_substring:
  (fd : any, buf : any, ofs : any, len : any, flags : any, addr : any) => any
  ;
export var getsockopt: (fd : any, opt : any) => any ;
export var setsockopt: (fd : any, opt : any, v : any) => any ;
export var getsockopt_int: (fd : any, opt : any) => any ;
export var setsockopt_int: (fd : any, opt : any, v : any) => any ;
export var getsockopt_optint: (fd : any, opt : any) => any ;
export var setsockopt_optint: (fd : any, opt : any, v : any) => any ;
export var getsockopt_float: (fd : any, opt : any) => any ;
export var setsockopt_float: (fd : any, opt : any, v : any) => any ;
export var getsockopt_error: (fd : any) => any ;
export var open_connection: (sockaddr : any) => any ;
export var shutdown_connection: (inchan : any) => any ;
export var establish_server: (server_fun : any, sockaddr : any) => any ;
export var gethostname: any ;
export var gethostbyname: any ;
export var gethostbyaddr: any ;
export var getprotobyname: any ;
export var getprotobynumber: any ;
export var getservbyname: any ;
export var getservbyport: any ;
export var getaddrinfo: (node : any, service : any, opts : any) => any ;
export var getnameinfo: (addr : any, opts : any) => any ;
export var tcgetattr: any ;
export var tcsetattr: any ;
export var tcsendbreak: any ;
export var tcdrain: any ;
export var tcflush: any ;
export var tcflow: any ;
export var setsid: any ;

