// Generated by BUCKLESCRIPT VERSION 1.9.2, PLEASE EDIT WITH CARE
'use strict';

var Demo$Liba = require("liba/src/demo.js");
var Demo$Libb = require("libb/src/demo.js");

var v = Demo$Liba.v + Demo$Libb.v | 0;

exports.v = v;
/* No side effect */
