
== Build system support

The BuckleScript compilation model is similar to OCaml native compiler.
If `b.ml` depends on `a.ml`, you have to compile `a.ml` *and* `a.mli`
first.


[NOTE]
======
The technical reason is that BuckleScript will generate intermediate
files with the extension `.cmj` which are later used for cross module
inlining, arity inference and other information.
======

=== BuckleScript build system: `bsb`

BuckleScript proivdes a native build tool on top of Google's  https://github.com/ninja-build/ninja/releases[ninja-build], 
it is designed for fast feedback loop (typically 100ms feedback loop) and works cross platform. 

[INFO]
======
Currently for non-Windows users, they needs install ninja first (version >= 1.7.1),
please don't be confused with the npm ninja, 
we are using Google's https://github.com/ninja-build/ninja/releases[ninja-build].
======

`bsb` can be running in any subdirectory, it is a schema based build tool, the schema is 
http://bloomberg.github.io/bucklescript/docson/#build-schema.json[available]

The build system is installed as `bsb.exe` in `bs-platform/bin/bsb.exe`, due to a known issue in npm, 
we create a JS wrapper (which is accessible in `.bin` too), so the user can call 
either `bsb`(slightly higher latency but symlinked into `.bin`) or `bsb.exe` 


Here is a *minimal* configuration:

.bsconfig.json
[source,js]
-----------  
{ 
  "name": "test", // package name, required <1>  
  "sources": 
     { "dir": "src"} // <2>
}
-----------
<1> It is an extension to JSON with comment support
<2> Here we did not list files, so all `.ml`, `.mli`, `.re`, `.rei` will be considered as source files


The entry point is `bsb.exe`,
it will check if there is already `build.ninja` in the build directory, 
if not or need regenerated it will generate a file  `build.ninja` 
and delegate the hard work to `ninja`.


The directory layout (after building) would be

-----------
.                                                                                                                    
├── lib                                                                                                                                                                                                                      
│   ├── bs                                                                                                           
│   │   ├── src                                                                                                      
│   │   └── test                                                                                                                                                                                                              
│   ├── js                                                                                                           
│   │   ├── src                                                                                                      
│   │   └── test
│   ├── amdjs // <1>     
│   │   ├── src                                                                                                      
│   │   └── test
│   ├── goog  // <2>                                                                                                
│   │   ├── src                       
│   │   └── test
│   └── ocaml                                                                                                        
├── scripts                                                                                                          
├── src                                                                                                              
└── test   
-----------  
<1> Will generate amdjs modules if flags are turned on
<2> Will generate goog modules if flags are turned on 

We wrap `bsb.exe` as `bsb` so that it will work across different platform.

.Watch mode
[source,sh]
--------------------
bsb -w 
--------------------





==== Build with other BuckleScript dependencies

List your dependency in `bs-dependencies` and install it via `npm install` as below:

.bsconfig.json
[source,js]
-----------
{
    "name": "bs-string",
    "version": "0.1.3",
    "bs-dependencies": [
        "bs-mocha" // <1>
    ],
    "sources": [
       .. .
    ],
    "generate-merlin" : true // <2>
}
-----------
<1> Yet another BuckleScript dependency
<2> bsb will generate merlin file for you

.package.json
[source,js]
-----------
{
 "dependencies": {
    "bs-mocha": "0.1.5"
    },
  ...
}
-----------

After your `npm install`, 
[source,sh]
----------
bsb -clean-world // <1>
bsb -make-world // <2>
----------
<1> Clean the binary artifact of current build and your dependency
<2> Build dependencies and lib itself


==== Mark your directory as dev only


Note sometimes, you have directories which are just tests that you don't need your dependent 
to build  in that case you can mark it as dev only

.bsconfig.json
[source,js]
-----------
{
        "sources" : {
                "dir" : "test",
                "type" : "dev" // <1>
        }
}
-----------
<1> directory `test` is in dev mode, it will not be built when used as a dependency



=== Build using Make
[WARNING]
========
`bsb` is officialy recommended build system, this section is listed here only for people who 
are curious about how the build works
========

BuckleScript distribution has `bsdep.exe` which has the same interface as `ocamldep`

Here is a simple Makefile to get started:

.Makefile
[source,make]
-------------
OCAMLC=bsc.exe # <1>
OCAMLDEP=bsdep.exe # <2>
SOURCE_LIST := src_a src_b
SOURCE_MLI  = $(addsuffix .mli, $(SOURCE_LIST))
SOURCE_ML   = $(addsuffix .ml, $(SOURCE_LIST))
TARGETS := $(addsuffix .cmj, $(SOURCE_LIST))
INCLUDES=
all: $(TARGETS)
.mli:.cmi
        $(OCAMLC) $(INCLUDES) $(COMPFLAGS)  -c $<
.ml:.cmj:
        $(OCAMLC) $(INCLUDES) $(COMPFLAGS)  -c $<
-include .depend
depend:
        $(OCAMLDEP) $(INCLUDES) $(SOURCE_ML) $(SOURCE_MLI) > .depend
-------------
<1> bsc.exe is the BuckleScript compiler
<2> ocamldep executable is part of the OCaml compiler installation

In theory, people need run `make depend && make all`, `make depend` will calculate dependency
while `make all` will do the job.

However, in practice, people used to use a file watch service,
take https://facebook.github.io/watchman/[watchman] for example, you need json configure

.build.json
[source,json]
-------------
[
    "trigger", ".", {
        "name": "build",
        "expression": ["pcre", "(\\.(ml|mll|mly|mli|sh|sh)$|Makefile)"], // <1>
        "command": ["./build.sh"],
        "append_files" : true
    }
]
-------------
<1> whenever such files changed, it will trigger `command` field to be run

.build.sh
[source,sh]
-----------
make -r -j8 all <1>
make depend // <2>
-----------
<1> build
<2> update the dependency


Now in your working directory, type `watchman -j < build.json` and enjoy the lightning build speed.
