
== Build system support

The BuckleScript compilation model is similar to OCaml native compiler.
If `b.ml` depends on `a.ml`, you have to compile `a.ml` *and* `a.mli`
first.


[NOTE]
======
The technical reason is that BuckleScript will generate intermediate
files with the extension `.cmj` which are later used for cross module
inlining, arity inference and other information.
======

=== Build with bsb 

BuckleScript proivdes a native build tool using https://github.com/ninja-build/ninja/releases[ninja], 
it is designed for fast feedback loop (typically 100ms feedback loop). 

[NOTE]
======
Currently user needs install ninja first (version >= 1.7.1)
======

It is a schema based build tool, the schema is 
http://bloomberg.github.io/bucklescript/docson/#build-schema.json[available]

The build system is installed as `bsb.exe` in `bs-platform/bin/bsb.exe`, due to a known issue in npm, 
we create a JS wrapper (which is accessible in `.bin` too), so the user can call 
either `bsb`(slightly higher latency but symlinked into `.bin`) or `bsb.exe` 


Here is a *minimal* configuration:

.bsconfig.json
[source,js]
-----------  
{ 
  "name": "test", // package name, required <1>  
  "sources": 
     { "dir": "src"} // <2>
}
-----------
<1> It is an extension to JSON with comment support
<2> Here we did not list files, so all `.ml`, `.mli`, `.re`, `.rei` will be considered as source files


The entry point is `bsb.exe`,
it will check if there is already `build.ninja` in the build directory, 
if not or need regenerated it will generate a file  `build.ninja` 
and delegate the hard work to `ninja`.


The directory layout (after building) would be

-----------
.                                                                                                                    
├── lib                                                                                                                                                                                                                      
│   ├── bs                                                                                                           
│   │   ├── src                                                                                                      
│   │   └── test                                                                                                                                                                                                              
│   ├── js                                                                                                           
│   │   ├── src                                                                                                      
│   │   └── test
│   ├── amdjs // <1>     
│   │   ├── src                                                                                                      
│   │   └── test
│   ├── goog  // <2>                                                                                                
│   │   ├── src                       
│   │   └── test
│   └── ocaml                                                                                                        
├── scripts                                                                                                          
├── src                                                                                                              
└── test   
-----------  
<1> Will generate amdjs modules if flags are turned on
<2> Will generate goog modules if flags are turned on 

We wrap `bsb.exe` as `bsb` so that it will work across different platform.

.Watch mode
[source,sh]
--------------------
bsb -w 
--------------------


=== Build using Make
BuckleScript distribution has `bsdep.exe` which has the same interface as `ocamldep`

Here is a simple Makefile to get started:

.Makefile
[source,make]
-------------
OCAMLC=bsc.exe # <1>
OCAMLDEP=bsdep.exe # <2>
SOURCE_LIST := src_a src_b
SOURCE_MLI  = $(addsuffix .mli, $(SOURCE_LIST))
SOURCE_ML   = $(addsuffix .ml, $(SOURCE_LIST))
TARGETS := $(addsuffix .cmj, $(SOURCE_LIST))
INCLUDES=
all: $(TARGETS)
.mli:.cmi
        $(OCAMLC) $(INCLUDES) $(COMPFLAGS)  -c $<
.ml:.cmj:
        $(OCAMLC) $(INCLUDES) $(COMPFLAGS)  -c $<
-include .depend
depend:
        $(OCAMLDEP) $(INCLUDES) $(SOURCE_ML) $(SOURCE_MLI) > .depend
-------------
<1> bsc.exe is the BuckleScript compiler
<2> ocamldep executable is part of the OCaml compiler installation

In theory, people need run `make depend && make all`, `make depend` will calculate dependency
while `make all` will do the job.

However, in practice, people used to use a file watch service,
take https://facebook.github.io/watchman/[watchman] for example, you need json configure

.build.json
[source,json]
-------------
[
    "trigger", ".", {
        "name": "build",
        "expression": ["pcre", "(\\.(ml|mll|mly|mli|sh|sh)$|Makefile)"], // <1>
        "command": ["./build.sh"],
        "append_files" : true
    }
]
-------------
<1> whenever such files changed, it will trigger `command` field to be run

.build.sh
[source,sh]
-----------
make -r -j8 all <1>
make depend // <2>
-----------
<1> build
<2> update the dependency


Now in your working directory, type `watchman -j < build.json` and enjoy the lightning build speed.
