
## Extended compiler options
BuckleScript inherits the command line arguments of the
http://caml.inria.fr/pub/docs/manual-ocaml/comp.html[OCaml compiler]. It
also adds several flags:

### -bs-main (single directory build)

[source,sh]
--------------------
bsc -bs-main main.ml
--------------------

`bsc` will build module `Main` and all its dependencies, when it
finishes, it will run `node main.js`.

[source,sh]
-----------------------
bsc -c -bs-main main.ml
-----------------------

The same as above, but will not run `node`.

### -bs-files

So that you can do

[source,sh]
---------------------------
bsc -c -bs-files *.ml *.mli
---------------------------

The compiler will sort the order of input files before starting
compilation.

BuckleScript supports two compilation mode, script mode and package
mode, in package mode, you have to provide `package.json` on top and set the options
`-bs-package-name`, `-bs-package-output`. In script mode, such flags are not needed

### -bs-package-name
The project name of your project, user is suggested to make it
consistent with the `name` field in `package.json`

### -bs-packge-output
The format is `module_system:oupt/path/relative/to/package.json`
Currently supported module systesms are: `commonjs`, `amdjs` and
`goog:<namespace>`

For example, when you want to use the `goog` module system, you can do
things like this:

[source,bash]
-----------------------------------------------------------
bsc -bs-package-name your_package -bs-package-output goog:lib/goog xx.ml
-----------------------------------------------------------


NOTE: User can supply multiple `-bs-package-output` at the same time.


You would then need a bundler for the different module systems:
`webpack` supports `commonjs` and `amdjs` while
`google closure compiler` supports all.

### -bs-gen-tds

Trigger the generation of TypeScript `.d.ts` files.
`bsc` has the ability to also emits `.d.ts` for better interaction with
typescript. This is still experimental.

For more options, please see the documentation of `bsc -help`.
