
## Extended compiler options
BuckleScript inherits the command line arguments of the
http://caml.inria.fr/pub/docs/manual-ocaml/comp.html[OCaml compiler]. It
also adds several flags:

### -bs-main (single directory build)

[source,sh]
--------------------
bsc.exe -bs-main Main
--------------------

`bsc.exe` will build module `Main` and all its dependencies, when it
finishes, it will run `node main.js`.

[source,sh]
-----------------------
bsc.exe -c -bs-main Main
-----------------------

The same as above, but will not run `node`.

### -bs-files

So that you can do

[source,sh]
---------------------------
bsc.exe -c -bs-files *.ml *.mli
---------------------------

The compiler will sort the order of input files before starting
compilation.

BuckleScript supports two compilation mode, script mode and package
mode, in package mode, you have to provide `package.json` on top and set the options
`-bs-package-name`, `-bs-package-output`. In script mode, such flags are not needed

### -bs-package-name
The project name of your project, user is suggested to make it
consistent with the `name` field in `package.json`

### -bs-packge-output
The format is `module_system:oupt/path/relative/to/package.json`
Currently supported module systesms are: `commonjs`, `amdjs` and
`goog:<namespace>`

For example, when you want to use the `goog` module system, you can do
things like this:

[source,bash]
-----------------------------------------------------------
bsc.exe -bs-package-name your_package -bs-package-output goog:lib/goog -c xx.ml
-----------------------------------------------------------


NOTE: User can supply multiple `-bs-package-output` at the same time.

For example:

[source,bash]
------------
bsc.exe -bs-package-name name -bs-package-output commonjs:lib/js -bs-package-output goog:lib/goog -bs-package-output amdjs:lib/amdjs -c x.ml
------------

It will generate `x.js` in `lib/js` as commonjs module, `lib/goog` as google module and `lib/amdjs` as amdjs module at the same time.

You would then need a bundler for the different module systems:
`webpack` supports `commonjs` and `amdjs` while
`google closure compiler` supports all.

### -bs-gen-tds

Trigger the generation of TypeScript `.d.ts` files.
`bsc.exe` has the ability to also emits `.d.ts` for better interaction with
typescript. This is still experimental.

For more options, please see the documentation of `bsc.exe -help`.

### -bs-no-warn-ffi-type

Turn off warnings on FFI type declarations

### -bs-eval

.Example
[source,sh]
----------
bsc.exe -dparsetree -drawlambda -bs-eval 'Js.log "hello"'
----------

[source,ocaml]
--------------
[ // <1>
  structure_item (//toplevel//[1,0+0]..[1,0+14])
    Pstr_eval
    expression (//toplevel//[1,0+0]..[1,0+14])
      Pexp_apply
      expression (//toplevel//[1,0+0]..[1,0+6])
        Pexp_ident "Js.log" (//toplevel//[1,0+0]..[1,0+6])
      [
        <label> ""
          expression (//toplevel//[1,0+7]..[1,0+14])
            Pexp_constant Const_string("hello",None)
      ]
]
// <2>
(setglobal Bs_internal_eval! (seq (js_dump "hello") (makeblock 0)))
// Generated by BUCKLESCRIPT VERSION 1.0.2 , PLEASE EDIT WITH CARE
'use strict';


console.log("hello");

/*  Not a pure module */
--------------
<1> Output by flag -dparsetree
<2> Output by flag -drawlambda

For this flag, it will not create any intermediate file, which is useful for
learning or troubleshooting.

### -bs-no-builtin-ppx-ml, -bs-no-builtin-ppx-mli

If users don't use any bs specific annotaions, user can explicitly turn it off.
Another use case is that users can use `-ppx` explicitly as below:

[source,ocaml]
--------------
bsc.exe -c -ppx bsppx.exe -bs-no-builtin-ppx-ml c.ml
--------------
