## Contributions

First, thanks for your interest in contribution,
there are plenty of ways in contributions, like blogging, sharing your experience,
open sourcing your libraries using BuckleScript, they are all deeply appreciated.

This section will focus on how to contribute to this repo.

### Development set-up

* Having https://opam.ocaml.org/[opam] installed

    opam switch 4.02.3+buckle-master # use our OCaml compiler
    opam install camlp4  <1>
+
`Camlp4` is used to generate OCaml code for processing large AST. (`j.ml` file), if you don't
change `j.ml` (most likely you won't), so you probably don't need it

* Having https://nodejs.org/[NodeJS] installed
* Having Make installed
* OS: Mac/Linux (Note BuckleScript works on Windows, but the dev mode is not tested)

**Below assume that you are working in `jscomp` directory, and that you've followed instructions from <<Minimal dependencies>> to build OCaml.**


### Contributing to `bsb.exe`

The build target is
[source,sh]
-----------
make bin/bsb.exe
-----------

So whenever you change files relevant to the build tool `bsb.exe`, try it and do some
test, if it works, send a pull request!


Note that for most binaries in BuckleScript, we also have a **release mode**, which will pack
all relevant files into a single file, this is important, since it will cut all our dev-dependencies,
so the user does not need install those tools.


You can verify it by typing
[source,sh]
----------
make snapshotml # see the diffs in jscomp/bin
----------

But please **don't commit** those changes in PR, it will cause painful merge conflicts


### Contributing to `bsc.exe`

[source,sh]
-----------
make bin/bsc.exe # build the compiler in dev mode
-----------

[source,sh]
-----------
make libs # build all libs using the dev compiler
-----------

There is also a snapshot mode,

[source,sh]
----------
make snapshotml
----------

This will actually snapshot your changes into a single ml file and used in npm distribution.
But please **don't commit** those changes in PR, it will cause painful merge conflicts

### Contributing to the runtime

BuckleScript runtime implementation is currently a mix of OCaml and
JavaScript. (`jscomp/runtime` directory). The JavaScript code is defined
in the `.ml` file using the `bs.raw` syntax extension.

The goal is to implement the runtime *purely in OCaml* and you can help
contribute.

Each new PR should include appropriate testing.

Currently all tests are in `jscomp/test` directory and you should either
add a new test file or modify an existing test which covers the part of
the compiler you modified.

* Add the filename in `jscomp/test/test.mllib`
* Add a suite test

The specification is in `jscomp/test/mt.ml`

For example some simple tests would be like:

[source,ocaml]
--------------
let suites : _ Mt.pair_suites =
   ["hey", (fun _ -> Eq(true, 3 > 2));
       "hi", (fun _ ->  Neq(2,3));
       "hello", (fun _ -> Approx(3.0, 3.0));
       "throw", (fun _ -> ThrowAny(fun _ -> raise 3))
       ]
let () = Mt.from_pair_suites __FILE__ suites
--------------

* Run the tests

Suppose you have mocha installed, if not, try `npm install mocha`

`mocha -R list jscomp/test/your_test_file.js`

* See the coverage

`npm run cover`

### Contributing to the documentation

You'll need http://asciidoctor.org/[Asciidoctor] installed. Modify the section you want in `site/docsource/`, then run `site/docsource/build.sh`.
