== FAQ

[qanda]


How to adapt your build system?::
  The BuckleScript compilation model is the same as the OCaml compiler.
  If `b.ml` depends on `a.ml`, you have to compile `a.ml` *and* `a.mli`
  first.
+
[NOTE]
======
The technical reason is that BuckleScript will generate intermediate
files with the extension `.cmj` which are later used for cross module
inlining, arity inference and other information.
======
Here is a simple Makefile to get started:
+
.Makefile
[source,make]
-------------
OCAMLC=bsc.exe # <1>
OCAMLDEP=ocamldep # <2>
SOURCE_LIST := src_a src_b
SOURCE_MLI  = $(addsuffix .mli, $(SOURCE_LIST))
SOURCE_ML   = $(addsuffix .ml, $(SOURCE_LIST))
TARGETS := $(addsuffix .cmj, $(SOURCE_LIST))
INCLUDES=
all: $(TARGETS)
%.cmi: %.mli
        $(OCAMLC) $(INCLUDES) $(COMPFLAGS)  -c $<
%.ml: %.cmj:
        $(OCAMLC) $(INCLUDES) $(COMPFLAGS)  -c $<
-include .depend
depend:
        $(OCAMLDEP) $(INCLUDES) $(SOURCE_ML) $(SOURCE_MLI) | sed -e 's/\.cmx/.cmj/g' > .depend
-------------
<1> bsc.exe is the BuckleScript compiler
<2> ocamldep executable is part of the OCaml compiler installation


How does IO work in browser?::
  In general, it is very hard to simulate IO in browser, we recommend users to write bindings to NodeJS directly for server side, or use `Js.log` in client side, see disucssions in {issues}/748[#748]

The compiler does not build?::
  In production mode, the compiler is a single file in
`jscomp/bin/compiler.ml`. If it is not compiling, make sure you have the
right OCaml compiler version. Currently the OCaml compiler is a
submodule of BuckleScript. Make sure the exact commit hash matches (we
only update the compiler occasionally).

Which version of JavaScript syntax does BuckleScript target?::
BuckleScript targets **ES5**.

Does BuckleScript work with merlin?::
  Yes, you need edit your `.merlin` file:
+
[source]
--------
B node_modules/bs-platform/lib/ocaml
S node_modules/bs-platform/lib/ocaml
FLG -ppx node_modules/bs-platform/bin/bsppx.exe
--------
+
Note there is a https://github.com/the-lambda-church/merlin/issues/568[upstream fix] in Merlin, make sure your merlin is updated

What polyfills does BuckleScript need?::

- _Math.imul_:
  This polyfill is needed for `int32` multiplication.
  BuckleScript provides this by default(when feature detection returns false), no action is
  required from the user.
- _TypedArray_:
  The TypedArray polyfill is not provided by BuckleScript and it's the
  responsibility of the user to bundle the desired polyfill implementation
  with the BuckleScript generated code.

  The following functions from OCaml stdlib
  require the TypedArray polyfill:

    * Int64.float_of_bits
    * Int64.bits_of_float
    * Int32.float_of_bits
    * Int32.bits_of_float
+
[WARNING]
=====

For the current BuckleScript version, if the user does not bundle the
TypedArray polyfill, the JavaScript engine does not support it and user used
functions mentioned above, the code will fail at runtime.
=====
