++++
<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="UTF-8">
    <title>Welcome to BuckleScript</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="stylesheets/normalize.css" media="screen">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="stylesheets/stylesheet.css" media="screen">
    <link rel="stylesheet" type="text/css" href="stylesheets/github-light.css" media="screen">
  </head>
  <body>
    <section class="page-header">
      <h1 class="project-name">BuckleScript: write JS faster, safer and smaller</h1>
      <h2 class="project-tagline"></h2>
      <a href="https://github.com/bucklescript/bucklescript" class="btn">View on GitHub</a>
      <a href="./Manual.html" class="btn">Manual</a>
      <a href="../bucklescript-playground/index.html" class="btn">Try it </a>
      <a href="./blog/index.html" class="btn"> Blogs</a>
    </section>

    <section class="main-content">
++++

BuckleScript is a backend for http://ocaml.org/[OCaml] which emits readable, modular and highly performant JavaScript.

#### Developer experience

BuckleScript probably has the _fastest_ JavaScript compiler.The compiler is compiled to both native code and JavaScript,
users can try the compiler in the https://bucklescript.github.io/bucklescript-playground[browser] and imagine how fast it would be for native backend.

#### Integration with existing JavaScript libraries

BuckleScript is one of the very few compilers which compiles an _existing typed language_ to readable JavaScript. It has the same
characteristics of typescript: one OCaml module compiled into one JavaScript module (AMDJS, CommonJS, or Google module) without name mangling.

#### It's OCaml !
- 30 years distilled research in PL and amazing effort of compiler engineering
- Native backends: AMD64, IA32, PowerPC, ARM, SPARC
- Language based OS: Mirage Unikernel

#### Installation

[source,sh]
-----------
npm install -g bs-platform
-----------

#### Enjoy!
++++
      <footer class="site-footer">
        <span class="site-footer-owner"><a href="https://github.com/bucklescript/bucklescript">BuckleScript</a> is open-sourced by <a href="https://github.com/bucklescript">Bloomberg L.P </a>.</span>

      </footer>

    </section>


  </body>
</html>
++++
