
== Js module

link:https://bucklescript.github.io/bucklescript/api/Js.html[API reference]

Js module is shipped with BuckleScript, both the namespace `Js` and `Node` are preserved.

////
Apparently tags don't work anymore...

[source,ocaml]
.Js Public types
-------------
include::../../jscomp/runtime/js.ml[tags=public_js_types]
-------------

[source,ocaml]
.Js Utility functions
-------------
include::../../jscomp/runtime/js.ml[tags=utility_functions]
-------------

[source,ocaml]
.Js Predefined JS values
-------------
include::../../jscomp/runtime/js.ml[tags=predefined_js_values]
-------------
////

=== Null and Undefined

BuckleScript does not deal with `null` and `undefined` on the language level.
Instead they are defined on the library level, represented by `Js.Null.empty`
and `Js.Undefined.empty` (and `Js.Null_undefined.empty`) types. But due to this
being Ocaml and all, we can't just pass these values off as if it was any type
we'd like it to be, so in order to actually use them we need to lift the type we
want to use them with. For this purpose BuckleScript defines the type `'a Js.null`,
`'a Js.undefined' and `'a Js.null_undefined` (for values that can be both
`null`, `undefined` and `'a`). As well as the corresponding modules `Js.Null`,
`Js.Undefined` and `Js.Null_undefined` for working with these types.

Here's an example showing `Js.Null` used directly:

[source,ocaml]
-------------
external get_prop_name_maybe : unit -> string Js.null = "" [@@bs.val]
external set_or_unset_prop : string -> int Js.null -> unit = "" [@@bs.val]

(* unset property if fond *)
let s = get_prop_name_maybe ()
let _ = Js.Null.iter s (function name -> set_or_unset_prop name Js.Null.empty)

(* set some other property *)
let _ = set_or_unset_prop "some_other_property" (Js.Null.return "")
-------------

You might also want to map these types to `option` for a friendlier and more
idiomatic API, if the distinction between `null` and `undefined` isn't important
to maintain:

[source,ocaml]
-------------
external try_some_thing : string Js.null -> int Js.null = ...

let try_some_thing_maybe ( v : string option) : int option =
  Js.Null.to_opt (try_some_thing (Js.Null.from_opt v))
-------------

=== Boolean

"Native" `bool` is for Bob-ish reasons not represented as `true` and `false`
literals in JavaScript. For interop you therefore need to use the `Js.boolean`
and its `Js.true_` and `Js.false_` values. There are also convenience functions
for coercing to and from `bool`: `Js.to_bool` and `Js.Boolean.to_js_boolean`.

=== Stable-ish submodules

_These APIs might change, but is considered mostly complete_

* link:../api/Js.Null.html[Js.Null]
* link:../api/Js.Undefined.html[Js.Undefined]
* link:../api/Js.Null_undefined.html[Js.Null_undefined]

* link:../api/Js.Array.html[Js.Array]
* link:../api/Js.Date.html[Js.Date]
* link:../api/Js.Math.html[Js.Math]
* link:../api/Js.Re.html[Js.Re]
* link:../api/Js.String.html[Js.String]
* link:../api/Js.Typed_array.html[Js.Typed_array]

=== Experimental/incomplete submodules

_Expect these APIs to change drastically, **use only if you accept breakage.**_

* link:../api/Js.Boolean.html[Js.Boolean]
* link:../api/Js.Dict.html[Js.Dict]
* link:../api/Js.Obj.html[Js.Obj]

=== Very experimental/internal submodules

*_Do not use these APIs unless absolutely necessary, they're mostly internal_*

* link:../api/Js_float.html[Js_float]
* link:../api/Js_int.html[Js_int]
* link:../api/Js_int64.html[Js_int64]
* link:../api/Js_json.html[Js.Json]
* link:../api/Js_nativeint.html[Js_nativeint]
* link:../api/Js_primitive.html[Js_primitive]
* link:../api/Js_types.html[Js.Types]
* link:../api/Js_unsafe.html[Js_unsafe]

== Node module

link:../api/Node.html[Node]

=== Submodules

* link:../api/Node_buffer.html[Node.Buffer]
* link:../api/Node_child_process.html[Node.Child_process]
* link:../api/Node_fs.html[Node.Fs]
* link:../api/Node_module.html[Node.Module]
* link:../api/Node_path.html[Node.Path]
* link:../api/Node_process.html[Node.Process]
