// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function makeContainer(text) {
  var container = document.createElement("div");
  container.className = "container";
  var title = document.createElement("div");
  title.className = "containerTitle";
  title.innerText = text;
  var content = document.createElement("div");
  content.className = "containerContent";
  container.appendChild(title);
  container.appendChild(content);
  document.body.appendChild(container);
  return content;
}

function makeProps(value, onChange, param) {
  return {
          value: value,
          onChange: onChange
        };
}

function make(_props) {
  return null;
}

var BuckleScript3987ReproOk = {
  makeProps: makeProps,
  make: make
};

React.createElement(make, makeProps("test", (function (param, param$1) {
            
          }), undefined));

function Gpr_3987_test$BuckleScript3987ReproOk2(Props) {
  return null;
}

var BuckleScript3987ReproOk2 = {
  make: Gpr_3987_test$BuckleScript3987ReproOk2
};

React.createElement(Gpr_3987_test$BuckleScript3987ReproOk2, {
      value: "test",
      onChange: (function (param, param$1) {
          
        })
    });

function Gpr_3987_test$BuckleScript3987ReproError(Props) {
  return null;
}

var BuckleScript3987ReproError = {
  make: Gpr_3987_test$BuckleScript3987ReproError
};

React.createElement(Gpr_3987_test$BuckleScript3987ReproError, {
      value: "test",
      onChange: (function (param, param$1) {
          
        })
    });

exports.makeContainer = makeContainer;
exports.BuckleScript3987ReproOk = BuckleScript3987ReproOk;
exports.BuckleScript3987ReproOk2 = BuckleScript3987ReproOk2;
exports.BuckleScript3987ReproError = BuckleScript3987ReproError;
/*  Not a pure module */
