// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Foo = require("Foo");
let Curry = require("rescript/lib/js/curry.js");

let React = {};

let Test = {};

function test(className) {
  return Curry._1(Foo, {
              className: className
            });
}

exports.React = React;
exports.Test = Test;
exports.test = test;
/* Foo Not a pure module */
