#!/usr/bin/env node
var cp = require("child_process");
var path = require("path");

var file = process.argv[2];
console.log(file);
var fmt = path.parse(file);

process.env.RES_DEBUG_FILE = 1;
var ninja = path.join(__dirname, "..", process.platform, "ninja.exe");
cp.execSync(`touch ${file} && ${ninja} ${fmt.dir}/${fmt.name}.cmj`, {
  stdio: [0, 1, 2]
});
