#########################################################################
#                                                                       #
#                                 OCaml                                 #
#                                                                       #
#            Xavier Leroy, projet Cristal, INRIA Rocquencourt           #
#                                                                       #
#   Copyright 1999 Institut National de Recherche en Informatique et    #
#   en Automatique.  All rights reserved.  This file is distributed     #
#   under the terms of the GNU Library General Public License, with     #
#   the special exception on linking described in file ../LICENSE.      #
#                                                                       #
#########################################################################

include Makefile.common

CFLAGS=-DOCAML_STDLIB_DIR='"$(LIBDIR)"' $(IFLEXDIR)

DBGO=d.$(O)
OBJS=$(COMMONOBJS:.o=.$(O)) win32.$(O) main.$(O)
DOBJS=$(OBJS:.$(O)=.$(DBGO)) instrtrace.$(DBGO)

ocamlrun$(EXE): libcamlrun.$(A) prims.$(O)
	$(MKEXE) -o ocamlrun$(EXE) prims.$(O) $(call SYSLIB,ws2_32) \
	         $(EXTRALIBS) libcamlrun.$(A)

ocamlrund$(EXE): libcamlrund.$(A) prims.$(O) main.$(O)
	$(MKEXE) -o ocamlrund$(EXE) $(BYTECCDBGCOMPOPTS) prims.$(O) \
	         $(call SYSLIB,ws2_32) $(EXTRALIBS) libcamlrund.$(A)

libcamlrun.$(A): $(OBJS)
	$(call MKLIB,libcamlrun.$(A),$(OBJS))

libcamlrund.$(A): $(DOBJS)
	$(call MKLIB,libcamlrund.$(A),$(DOBJS))

%.$(O): %.c
	$(CC) $(CFLAGS) $(BYTECCCOMPOPTS) -c $<

%.$(DBGO): %.c
	$(CC) $(CFLAGS) $(BYTECCDBGCOMPOPTS) -c -o $@ $<

.depend.nt: .depend
	rm -f .depend.win32
	echo "win32.o: win32.c \\" >> .depend.win32
	echo " caml/fail.h caml/compatibility.h caml/misc.h \\" >> .depend.win32
	echo " caml/config.h ../config/m.h ../config/s.h \\" >> .depend.win32
	echo " caml/mlvalues.h caml/memory.h caml/gc.h \\" >> .depend.win32
	echo " caml/major_gc.h caml/freelist.h caml/minor_gc.h \\" >> .depend.win32
	echo " caml/osdeps.h caml/signals.h" >> .depend.win32
	cat .depend >> .depend.win32
	sed -e '/\.d\.o/q' -e 's/^\(.*\)\.o:/\1.$$(O) \1.$$(DBGO):/' \
	    .depend.win32 > .depend.nt
	rm -f .depend.win32

include .depend.nt
