// Generated by ReScript, PLEASE EDIT WITH CARE


function getName(t) {
  return t.renamed;
}

function getName$p(t) {
  return t.renamed;
}

function getAge(t) {
  return t.age;
}

function getAge$p(t) {
  return t.age;
}

let user = {
  TAG: "User",
  renamed: "Corentin",
  age: 35
};

export {
  user,
  getName,
  getName$p,
  getAge,
  getAge$p,
}
/* No side effect */
