// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mt from "./mt.mjs";

let suites = {
  contents: /* [] */0
};

let test_id = {
  contents: 0
};

function eq(loc, x, y) {
  test_id.contents = test_id.contents + 1 | 0;
  suites.contents = {
    hd: [
      loc + (" id " + test_id.contents.toString()),
      () => ({
        TAG: "Eq",
        _0: x,
        _1: y
      })
    ],
    tl: suites.contents
  };
}

function f(h) {
  return h.x.y.z;
}

function f2(h) {
  return h.x.y.z;
}

function f3(h, x, y) {
  return h.paint(x, y).draw(x, y);
}

function f4(h, x, y) {
  h.paint = [
    x,
    y
  ];
  h.paint.draw = [
    x,
    y
  ];
}

eq("File \"chain_code_test.res\", line 27, characters 12-19", 32, ({
  x: {
    y: {
      z: 32
    }
  }
}).x.y.z);

Mt.from_pair_suites("Chain_code_test", suites.contents);

export {
  suites,
  test_id,
  eq,
  f,
  f2,
  f3,
  f4,
}
/*  Not a pure module */
