// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "rescript/lib/es6/Js_dict.js";

let dict = {};

dict["someKey1"] = 1;

dict["someKey2"] = 2;

let asArray = Js_dict.values(dict);

export {
  dict,
  asArray,
}
/*  Not a pure module */
