first directive;
second directive;
// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Belt_Array = require("rescript/lib/js/belt_Array.js");

let a = Belt_Array.forEach;

exports.a = a;
/* No side effect */
