// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Mt = require("./mt.js");
let Primitive_int = require("rescript/lib/js/primitive_int.js");

let suites = {
  contents: /* [] */0
};

let test_id = {
  contents: 0
};

function eq(loc, x, y) {
  test_id.contents = test_id.contents + 1 | 0;
  suites.contents = {
    hd: [
      loc + (" id " + test_id.contents.toString()),
      () => ({
        TAG: "Eq",
        _0: x,
        _1: y
      })
    ],
    tl: suites.contents
  };
}

function add(suite) {
  suites.contents = {
    hd: suite,
    tl: suites.contents
  };
}

add([
  "File \"div_by_zero_test.res\", line 14, characters 7-14",
  () => ({
    TAG: "ThrowAny",
    _0: () => {
      Primitive_int.div(3, 0);
    }
  })
]);

add([
  "File \"div_by_zero_test.res\", line 15, characters 7-14",
  () => ({
    TAG: "ThrowAny",
    _0: () => {
      Primitive_int.mod_(3, 0);
    }
  })
]);

function div(x, y) {
  return Primitive_int.div(x, y) + 3 | 0;
}

Mt.from_pair_suites("Div_by_zero_test", suites.contents);

exports.suites = suites;
exports.test_id = test_id;
exports.eq = eq;
exports.add = add;
exports.div = div;
/*  Not a pure module */
