// Generated by ReScript, PLEASE EDIT WITH CARE


function u() {
  return xx(3);
}

let Textarea = {};

let $$Int32Array = {};

function v() {
  let u = new TextArea();
  u.minHeight = 3;
  return u.minHeight;
}

function f() {
  let v = new Int32Array(32);
  v[0] = 3;
  return v[0];
}

let a = true;

let b = false;

let c = null;

let d;

export {
  u,
  a,
  b,
  c,
  d,
  Textarea,
  $$Int32Array,
  v,
  f,
}
/* No side effect */
