// Generated by ReScript, PLEASE EDIT WITH CARE


let overflow_dec_i32_number = 272872590;

let overflow_dec_i32_number_2 = 0;

let not_overflow_dec_i32_number_3 = -1;

let overflow_hex_i32_number = -1;

export {
  overflow_dec_i32_number,
  overflow_dec_i32_number_2,
  not_overflow_dec_i32_number_3,
  overflow_hex_i32_number,
}
/* No side effect */
