// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Belt_Id = require("rescript/lib/js/Belt_Id.js");
let Belt_Map = require("rescript/lib/js/Belt_Map.js");
let Primitive_object = require("rescript/lib/js/Primitive_object.js");

let cmp = Primitive_object.compare;

let IntCmp = Belt_Id.MakeComparable({
  cmp: cmp
});

let m = Belt_Map.make(IntCmp);

let m$1 = Belt_Map.set(m, 0, "test");

exports.IntCmp = IntCmp;
exports.m = m$1;
/* IntCmp Not a pure module */
