// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mt from "./mt.mjs";

function f(x) {
  return x;
}

function f2(x) {
  return x;
}

function f4(x) {
  return x;
}

let u = 1;

let v = true;

let suites_0 = [
  "?bool_eq_caml_bool",
  param => ({
    TAG: "Eq",
    _0: u,
    _1: true
  })
];

let suites_1 = {
  hd: [
    "js_bool_eq_js_bool",
    param => ({
      TAG: "Eq",
      _0: v,
      _1: true
    })
  ],
  tl: {
    hd: [
      "js_bool_neq_acml_bool",
      param => ({
        TAG: "Eq",
        _0: true,
        _1: true === true
      })
    ],
    tl: /* [] */0
  }
};

let suites = {
  hd: suites_0,
  tl: suites_1
};

function ff(u) {
  if (u === true) {
    return 1;
  } else {
    return 2;
  }
}

function fi(x, y) {
  return x === y;
}

function fb(x, y) {
  return x === y;
}

function fadd(x, y) {
  return x + y | 0;
}

function ffadd(x, y) {
  return x + y;
}

function ss(x) {
  return "xx" > x;
}

function bb(x) {
  return [
    true > x,
    false,
    true,
    true <= x,
    false,
    false < x,
    false >= x,
    true
  ];
}

let consts = [
  false,
  false,
  true,
  false,
  true,
  false,
  true,
  true
];

let bool_array = [
  true,
  false
];

Mt.from_pair_suites("Js_bool_test", suites);

let f3 = true;

export {
  f,
  f2,
  f4,
  f3,
  u,
  v,
  suites,
  ff,
  fi,
  fb,
  fadd,
  ffadd,
  ss,
  bb,
  consts,
  bool_array,
}
/*  Not a pure module */
