// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Foo_class from "xx/foo_class";

function f() {
  return new Foo_class(3);
}

function v() {
  return Foo_class.ff(3);
}

export {
  f,
  v,
}
/* xx/foo_class Not a pure module */
