// Generated by ReScript, PLEASE EDIT WITH CARE


let structural_obj = {
  x: {
    y: {
      z: 3
    }
  }
};

let f_record = {
  x: {
    y: {
      z: 3
    }
  }
};

export {
  structural_obj,
  f_record,
}
/* No side effect */
