// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mt from "./mt.mjs";

function is_block(x) {
  return typeof x !== "number";
}

let suites_0 = [
  "is_block_test1",
  param => ({
    TAG: "Eq",
    _0: false,
    _1: "number" !== "number"
  })
];

let suites_1 = {
  hd: [
    "is_block_test2",
    param => ({
      TAG: "Eq",
      _0: true,
      _1: typeof ({
        hd: 3,
        tl: /* [] */0
      }) !== "number"
    })
  ],
  tl: {
    hd: [
      "is_block_test3",
      param => ({
        TAG: "Eq",
        _0: true,
        _1: "string" !== "number"
      })
    ],
    tl: {
      hd: [
        "is_block_test4",
        param => ({
          TAG: "Eq",
          _0: false,
          _1: "number" !== "number"
        })
      ],
      tl: /* [] */0
    }
  }
};

let suites = {
  hd: suites_0,
  tl: suites_1
};

Mt.from_pair_suites("Obj_magic_test", suites);

export {
  is_block,
  suites,
}
/*  Not a pure module */
