// Generated by ReScript, PLEASE EDIT WITH CARE


let a = {
  x: 3,
  y: {
    hd: 1,
    tl: {
      hd: 2,
      tl: {
        hd: 3,
        tl: /* [] */0
      }
    }
  }
};

export {
  a,
}
/* No side effect */
