// Generated by ReScript, PLEASE EDIT WITH CARE


function u(rl) {
  return rl.on("line", x => {
    console.log(x);
  }).on("close", () => {
    console.log("finished");
  });
}

function xx(h) {
  return h.send("x").hi;
}

function yy(h) {
  return h.send("x");
}

export {
  u,
  xx,
  yy,
}
/* No side effect */
