// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_object from "rescript/lib/es6/Primitive_object.js";

let vicky = {};

let teacher = {};

Primitive_object.updateDummy(vicky, {
  taughtBy: teacher
});

Primitive_object.updateDummy(teacher, {
  students: [vicky]
});

export {
  vicky,
  teacher,
}
/* No side effect */
