// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Primitive_module = require("rescript/lib/js/primitive_module.js");

function Make(X) {
  let f = () => {};
  let M = {
    f: f
  };
  return {
    M: M
  };
}

let B = Primitive_module.init([
  "recursive_unbound_module_test.res",
  14,
  11
], {
  TAG: "Module",
  _0: [[
      {
        TAG: "Module",
        _0: [[
            "Function",
            "f"
          ]]
      },
      "M"
    ]]
});

function f() {
  
}

let M = {
  f: f
};

Primitive_module.update({
  TAG: "Module",
  _0: [[
      {
        TAG: "Module",
        _0: [[
            "Function",
            "f"
          ]]
      },
      "M"
    ]]
}, B, {
  M: M
});

let A;

exports.Make = Make;
exports.A = A;
exports.B = B;
/* B Not a pure module */
