// Generated by ReScript, PLEASE EDIT WITH CARE

import * as FileJs from "./File.js";

let foo = FileJs.foo;

function foo2(prim) {
  return FileJs.foo2(prim);
}

let bar = foo;

export {
  foo,
  foo2,
  bar,
}
/* foo Not a pure module */
