// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Primitive_exceptions = require("rescript/lib/js/primitive_exceptions.js");

let U = /* @__PURE__ */Primitive_exceptions.create("Test_common.U");

let H = /* @__PURE__ */Primitive_exceptions.create("Test_common.H");

exports.U = U;
exports.H = H;
/* No side effect */
