// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Belt_Array = require("rescript/lib/js/belt_Array.js");

let const_v = Belt_Array.concat([
  1,
  2
], [3]);

exports.const_v = const_v;
/* const_v Not a pure module */
