// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_MapString from "rescript/lib/es6/Belt_MapString.js";

let v = Belt_MapString.isEmpty(undefined);

export {
  v,
}
/* v Not a pure module */
