// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/Belt_Array.js";

let v = {
  contents: 32
};

v.contents = 0;

let N = {
  a: 3,
  v: v
};

let v$1 = {
  contents: 32
};

let NN = {
  a: 3,
  v: v$1
};

let get = Belt_Array.get;

let getExn = Belt_Array.getExn;

let set = Belt_Array.set;

let setExn = Belt_Array.setExn;

let shuffleInPlace = Belt_Array.shuffleInPlace;

let shuffle = Belt_Array.shuffle;

let reverseInPlace = Belt_Array.reverseInPlace;

let reverse = Belt_Array.reverse;

let make = Belt_Array.make;

let range = Belt_Array.range;

let rangeBy = Belt_Array.rangeBy;

let makeByU = Belt_Array.makeByU;

let makeBy = Belt_Array.makeBy;

let makeByAndShuffleU = Belt_Array.makeByAndShuffleU;

let makeByAndShuffle = Belt_Array.makeByAndShuffle;

let zip = Belt_Array.zip;

let zipByU = Belt_Array.zipByU;

let zipBy = Belt_Array.zipBy;

let unzip = Belt_Array.unzip;

let concat = Belt_Array.concat;

let concatMany = Belt_Array.concatMany;

let slice = Belt_Array.slice;

let sliceToEnd = Belt_Array.sliceToEnd;

let fill = Belt_Array.fill;

let blit = Belt_Array.blit;

let blitUnsafe = Belt_Array.blitUnsafe;

let forEachU = Belt_Array.forEachU;

let forEach = Belt_Array.forEach;

let mapU = Belt_Array.mapU;

let map = Belt_Array.map;

let flatMapU = Belt_Array.flatMapU;

let flatMap = Belt_Array.flatMap;

let getByU = Belt_Array.getByU;

let getBy = Belt_Array.getBy;

let getIndexByU = Belt_Array.getIndexByU;

let getIndexBy = Belt_Array.getIndexBy;

let keepU = Belt_Array.keepU;

let keep = Belt_Array.keep;

let keepWithIndexU = Belt_Array.keepWithIndexU;

let keepWithIndex = Belt_Array.keepWithIndex;

let keepMapU = Belt_Array.keepMapU;

let keepMap = Belt_Array.keepMap;

let forEachWithIndexU = Belt_Array.forEachWithIndexU;

let forEachWithIndex = Belt_Array.forEachWithIndex;

let mapWithIndexU = Belt_Array.mapWithIndexU;

let mapWithIndex = Belt_Array.mapWithIndex;

let partitionU = Belt_Array.partitionU;

let partition = Belt_Array.partition;

let reduceU = Belt_Array.reduceU;

let reduce = Belt_Array.reduce;

let reduceReverseU = Belt_Array.reduceReverseU;

let reduceReverse = Belt_Array.reduceReverse;

let reduceReverse2U = Belt_Array.reduceReverse2U;

let reduceReverse2 = Belt_Array.reduceReverse2;

let reduceWithIndexU = Belt_Array.reduceWithIndexU;

let reduceWithIndex = Belt_Array.reduceWithIndex;

let joinWithU = Belt_Array.joinWithU;

let joinWith = Belt_Array.joinWith;

let someU = Belt_Array.someU;

let some = Belt_Array.some;

let everyU = Belt_Array.everyU;

let every = Belt_Array.every;

let every2U = Belt_Array.every2U;

let every2 = Belt_Array.every2;

let some2U = Belt_Array.some2U;

let some2 = Belt_Array.some2;

let cmpU = Belt_Array.cmpU;

let cmp = Belt_Array.cmp;

let eqU = Belt_Array.eqU;

let eq = Belt_Array.eq;

let initU = Belt_Array.initU;

let init = Belt_Array.init;

let a = 3;

export {
  get,
  getExn,
  set,
  setExn,
  shuffleInPlace,
  shuffle,
  reverseInPlace,
  reverse,
  make,
  range,
  rangeBy,
  makeByU,
  makeBy,
  makeByAndShuffleU,
  makeByAndShuffle,
  zip,
  zipByU,
  zipBy,
  unzip,
  concat,
  concatMany,
  slice,
  sliceToEnd,
  fill,
  blit,
  blitUnsafe,
  forEachU,
  forEach,
  mapU,
  map,
  flatMapU,
  flatMap,
  getByU,
  getBy,
  getIndexByU,
  getIndexBy,
  keepU,
  keep,
  keepWithIndexU,
  keepWithIndex,
  keepMapU,
  keepMap,
  forEachWithIndexU,
  forEachWithIndex,
  mapWithIndexU,
  mapWithIndex,
  partitionU,
  partition,
  reduceU,
  reduce,
  reduceReverseU,
  reduceReverse,
  reduceReverse2U,
  reduceReverse2,
  reduceWithIndexU,
  reduceWithIndex,
  joinWithU,
  joinWith,
  someU,
  some,
  everyU,
  every,
  every2U,
  every2,
  some2U,
  some2,
  cmpU,
  cmp,
  eqU,
  eq,
  initU,
  init,
  N,
  NN,
  a,
  v,
}
/*  Not a pure module */
