// Generated by ReScript, PLEASE EDIT WITH CARE


function foo(t) {
  if (typeof t !== "object") {
    console.log("A");
    return ;
  }
  console.log("B" + t.name);
}

var X = {
  foo: foo,
  x: 42
};

var Y = {
  x: ""
};

export {
  X ,
  Y ,
}
/* No side effect */
