// Generated by ReScript, PLEASE EDIT WITH CARE


function JSXV4(props) {
  return props.x + props.y;
}

function JSXV4$CompV4(props) {
  return props.x + props.y;
}

var CompV4 = {
  make: JSXV4$CompV4
};

function JSXV4$CompV3(Props) {
  return Props.x + Props.y;
}

var CompV3 = {
  make: JSXV4$CompV3
};

var make = JSXV4;

export {
  make ,
  CompV4 ,
  CompV3 ,
}
/* No side effect */
