// Generated by ReScript, PLEASE EDIT WITH CARE


let Inner = {};

let Outer = {
  Inner: Inner
};

let OuterAlias;

let InnerAlias;

let q = 42;

export {
  Outer,
  OuterAlias,
  InnerAlias,
  q,
}
/* No side effect */
