// Generated by ReScript, PLEASE EDIT WITH CARE


let st = {
  crop: undefined,
  "fp-z": undefined
};

let st2 = {
  crop: undefined,
  "fp-z": undefined
};

export {
  st,
  st2,
}
/* No side effect */
