// Generated by ReScript, PLEASE EDIT WITH CARE


function noConversion(x) {
  return x;
}

function testConvertNestedRecordFromOtherFile(x) {
  return x;
}

export default {
  noConversion ,
  testConvertNestedRecordFromOtherFile ,
}
/* No side effect */
